// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Mogri.Clients.SdForgeNeo.Api;
using Mogri.Clients.SdForgeNeo.App_id;
using Mogri.Clients.SdForgeNeo.Assets;
using Mogri.Clients.SdForgeNeo.Call;
using Mogri.Clients.SdForgeNeo.Cancel;
using Mogri.Clients.SdForgeNeo.Component_server;
using Mogri.Clients.SdForgeNeo.Config;
using Mogri.Clients.SdForgeNeo.Controlnet;
using Mogri.Clients.SdForgeNeo.Custom_component;
using Mogri.Clients.SdForgeNeo.Dev;
using Mogri.Clients.SdForgeNeo.FaviconIco;
using Mogri.Clients.SdForgeNeo.FileNamespace;
using Mogri.Clients.SdForgeNeo.Heartbeat;
using Mogri.Clients.SdForgeNeo.Info;
using Mogri.Clients.SdForgeNeo.Internal;
using Mogri.Clients.SdForgeNeo.Login;
using Mogri.Clients.SdForgeNeo.Login_check;
using Mogri.Clients.SdForgeNeo.Logout;
using Mogri.Clients.SdForgeNeo.Monitoring;
using Mogri.Clients.SdForgeNeo.Queue;
using Mogri.Clients.SdForgeNeo.Reset;
using Mogri.Clients.SdForgeNeo.RobotsTxt;
using Mogri.Clients.SdForgeNeo.Run;
using Mogri.Clients.SdForgeNeo.Sd_extra_networks;
using Mogri.Clients.SdForgeNeo.Sdapi;
using Mogri.Clients.SdForgeNeo.StartupEvents;
using Mogri.Clients.SdForgeNeo.Static;
using Mogri.Clients.SdForgeNeo.StreamNamespace;
using Mogri.Clients.SdForgeNeo.ThemeCss;
using Mogri.Clients.SdForgeNeo.Token;
using Mogri.Clients.SdForgeNeo.Upload;
using Mogri.Clients.SdForgeNeo.Upload_progress;
using Mogri.Clients.SdForgeNeo.User;
using Mogri.Clients.SdForgeNeo.WithPath_or_url;
using Mogri.Clients.SdForgeNeo.WithUrl_path;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mogri.Clients.SdForgeNeo
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SdForgeNeoClient : BaseRequestBuilder
    {
        /// <summary>The api property</summary>
        public global::Mogri.Clients.SdForgeNeo.Api.ApiRequestBuilder Api
        {
            get => new global::Mogri.Clients.SdForgeNeo.Api.ApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The app_id property</summary>
        public global::Mogri.Clients.SdForgeNeo.App_id.App_idRequestBuilder App_id
        {
            get => new global::Mogri.Clients.SdForgeNeo.App_id.App_idRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assets property</summary>
        public global::Mogri.Clients.SdForgeNeo.Assets.AssetsRequestBuilder Assets
        {
            get => new global::Mogri.Clients.SdForgeNeo.Assets.AssetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The call property</summary>
        public global::Mogri.Clients.SdForgeNeo.Call.CallRequestBuilder Call
        {
            get => new global::Mogri.Clients.SdForgeNeo.Call.CallRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cancel property</summary>
        public global::Mogri.Clients.SdForgeNeo.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Mogri.Clients.SdForgeNeo.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The component_server property</summary>
        public global::Mogri.Clients.SdForgeNeo.Component_server.Component_serverRequestBuilder Component_server
        {
            get => new global::Mogri.Clients.SdForgeNeo.Component_server.Component_serverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The config property</summary>
        public global::Mogri.Clients.SdForgeNeo.Config.ConfigRequestBuilder Config
        {
            get => new global::Mogri.Clients.SdForgeNeo.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The controlnet property</summary>
        public global::Mogri.Clients.SdForgeNeo.Controlnet.ControlnetRequestBuilder Controlnet
        {
            get => new global::Mogri.Clients.SdForgeNeo.Controlnet.ControlnetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The custom_component property</summary>
        public global::Mogri.Clients.SdForgeNeo.Custom_component.Custom_componentRequestBuilder Custom_component
        {
            get => new global::Mogri.Clients.SdForgeNeo.Custom_component.Custom_componentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dev property</summary>
        public global::Mogri.Clients.SdForgeNeo.Dev.DevRequestBuilder Dev
        {
            get => new global::Mogri.Clients.SdForgeNeo.Dev.DevRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The faviconIco property</summary>
        public global::Mogri.Clients.SdForgeNeo.FaviconIco.FaviconIcoRequestBuilder FaviconIco
        {
            get => new global::Mogri.Clients.SdForgeNeo.FaviconIco.FaviconIcoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The file property</summary>
        public global::Mogri.Clients.SdForgeNeo.FileNamespace.FileRequestBuilder File
        {
            get => new global::Mogri.Clients.SdForgeNeo.FileNamespace.FileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The heartbeat property</summary>
        public global::Mogri.Clients.SdForgeNeo.Heartbeat.HeartbeatRequestBuilder Heartbeat
        {
            get => new global::Mogri.Clients.SdForgeNeo.Heartbeat.HeartbeatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public global::Mogri.Clients.SdForgeNeo.Info.InfoRequestBuilder Info
        {
            get => new global::Mogri.Clients.SdForgeNeo.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The internal property</summary>
        public global::Mogri.Clients.SdForgeNeo.Internal.InternalRequestBuilder Internal
        {
            get => new global::Mogri.Clients.SdForgeNeo.Internal.InternalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::Mogri.Clients.SdForgeNeo.Login.LoginRequestBuilder Login
        {
            get => new global::Mogri.Clients.SdForgeNeo.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login_check property</summary>
        public global::Mogri.Clients.SdForgeNeo.Login_check.Login_checkRequestBuilder Login_check
        {
            get => new global::Mogri.Clients.SdForgeNeo.Login_check.Login_checkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::Mogri.Clients.SdForgeNeo.Logout.LogoutRequestBuilder Logout
        {
            get => new global::Mogri.Clients.SdForgeNeo.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The monitoring property</summary>
        public global::Mogri.Clients.SdForgeNeo.Monitoring.MonitoringRequestBuilder Monitoring
        {
            get => new global::Mogri.Clients.SdForgeNeo.Monitoring.MonitoringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queue property</summary>
        public global::Mogri.Clients.SdForgeNeo.Queue.QueueRequestBuilder Queue
        {
            get => new global::Mogri.Clients.SdForgeNeo.Queue.QueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reset property</summary>
        public global::Mogri.Clients.SdForgeNeo.Reset.ResetRequestBuilder Reset
        {
            get => new global::Mogri.Clients.SdForgeNeo.Reset.ResetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The robotsTxt property</summary>
        public global::Mogri.Clients.SdForgeNeo.RobotsTxt.RobotsTxtRequestBuilder RobotsTxt
        {
            get => new global::Mogri.Clients.SdForgeNeo.RobotsTxt.RobotsTxtRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The run property</summary>
        public global::Mogri.Clients.SdForgeNeo.Run.RunRequestBuilder Run
        {
            get => new global::Mogri.Clients.SdForgeNeo.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sd_extra_networks property</summary>
        public global::Mogri.Clients.SdForgeNeo.Sd_extra_networks.Sd_extra_networksRequestBuilder Sd_extra_networks
        {
            get => new global::Mogri.Clients.SdForgeNeo.Sd_extra_networks.Sd_extra_networksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sdapi property</summary>
        public global::Mogri.Clients.SdForgeNeo.Sdapi.SdapiRequestBuilder Sdapi
        {
            get => new global::Mogri.Clients.SdForgeNeo.Sdapi.SdapiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The startupEvents property</summary>
        public global::Mogri.Clients.SdForgeNeo.StartupEvents.StartupEventsRequestBuilder StartupEvents
        {
            get => new global::Mogri.Clients.SdForgeNeo.StartupEvents.StartupEventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The static property</summary>
        public global::Mogri.Clients.SdForgeNeo.Static.StaticRequestBuilder Static
        {
            get => new global::Mogri.Clients.SdForgeNeo.Static.StaticRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stream property</summary>
        public global::Mogri.Clients.SdForgeNeo.StreamNamespace.StreamRequestBuilder Stream
        {
            get => new global::Mogri.Clients.SdForgeNeo.StreamNamespace.StreamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The themeCss property</summary>
        public global::Mogri.Clients.SdForgeNeo.ThemeCss.ThemeCssRequestBuilder ThemeCss
        {
            get => new global::Mogri.Clients.SdForgeNeo.ThemeCss.ThemeCssRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::Mogri.Clients.SdForgeNeo.Token.TokenRequestBuilder Token
        {
            get => new global::Mogri.Clients.SdForgeNeo.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::Mogri.Clients.SdForgeNeo.Upload.UploadRequestBuilder Upload
        {
            get => new global::Mogri.Clients.SdForgeNeo.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload_progress property</summary>
        public global::Mogri.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder Upload_progress
        {
            get => new global::Mogri.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Mogri.Clients.SdForgeNeo.User.UserRequestBuilder User
        {
            get => new global::Mogri.Clients.SdForgeNeo.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.SdForgeNeo.SdForgeNeoClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SdForgeNeoClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
        /// <summary>
        /// Main
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Main
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> HeadAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> HeadAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToHeadRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Main
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/html");
            return requestInfo;
        }
        /// <summary>
        /// Main
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToHeadRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToHeadRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.HEAD, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/html");
            return requestInfo;
        }
        /// <summary>
        /// Builds and executes requests for operations under \file={path_or_url}
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.SdForgeNeo.WithPath_or_url.WithPath_or_urlRequestBuilder"/></returns>
        /// <param name="path_or_url">The path parameter: path_or_url</param>
        public global::Mogri.Clients.SdForgeNeo.WithPath_or_url.WithPath_or_urlRequestBuilder WithPath_or_url(string path_or_url)
        {
            if(string.IsNullOrEmpty(path_or_url)) throw new ArgumentNullException(nameof(path_or_url));
            return new global::Mogri.Clients.SdForgeNeo.WithPath_or_url.WithPath_or_urlRequestBuilder(PathParameters, RequestAdapter, path_or_url);
        }
        /// <summary>
        /// Builds and executes requests for operations under \proxy={url_path}
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.SdForgeNeo.WithUrl_path.WithUrl_pathRequestBuilder"/></returns>
        /// <param name="url_path">The path parameter: url_path</param>
        public global::Mogri.Clients.SdForgeNeo.WithUrl_path.WithUrl_pathRequestBuilder WithUrl_path(string url_path)
        {
            if(string.IsNullOrEmpty(url_path)) throw new ArgumentNullException(nameof(url_path));
            return new global::Mogri.Clients.SdForgeNeo.WithUrl_path.WithUrl_pathRequestBuilder(PathParameters, RequestAdapter, url_path);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SdForgeNeoClientGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SdForgeNeoClientHeadRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
