// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Mogri.Clients.ComfyUi.Api.Assets.Hash.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mogri.Clients.ComfyUi.Api.Assets.Hash
{
    /// <summary>
    /// Builds and executes requests for operations under \api\assets\hash
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HashRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Mogri.Clients.ComfyUi.api.assets.hash.item collection</summary>
        /// <param name="position">Blake3 hash of the asset in format &apos;blake3:hex_digest&apos;</param>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Hash.Item.WithHashItemRequestBuilder"/></returns>
        public global::Mogri.Clients.ComfyUi.Api.Assets.Hash.Item.WithHashItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("hash", position);
                return new global::Mogri.Clients.ComfyUi.Api.Assets.Hash.Item.WithHashItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Hash.HashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HashRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/hash", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Hash.HashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HashRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/hash", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
