// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Mogri.Clients.ComfyUi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mogri.Clients.ComfyUi.Api.Jobs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\jobs\{job_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithJob_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Jobs.Item.WithJob_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithJob_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/jobs/{job_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Jobs.Item.WithJob_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithJob_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/jobs/{job_id}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve complete details for a specific job including workflow and outputs.Used for detail views, workflow re-execution, and debugging.
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Models.JobDetailResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse>(requestInfo, global::Mogri.Clients.ComfyUi.Models.JobDetailResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve complete details for a specific job including workflow and outputs.Used for detail views, workflow re-execution, and debugging.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Api.Jobs.Item.WithJob_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mogri.Clients.ComfyUi.Api.Jobs.Item.WithJob_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mogri.Clients.ComfyUi.Api.Jobs.Item.WithJob_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithJob_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
