// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \stream\{session_hash}\{run}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRunItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MobileDiffusion.Clients.SdForgeNeo.stream.item.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item.Item.WithComponent_ItemRequestBuilder"/></returns>
        public global::MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item.Item.WithComponent_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("component_id", position);
                return new global::MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item.Item.WithComponent_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the MobileDiffusion.Clients.SdForgeNeo.stream.item.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item.Item.WithComponent_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item.Item.WithComponent_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("component_id", position);
                return new global::MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item.Item.WithComponent_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item.WithRunItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRunItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stream/{session_hash}/{run}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.StreamNamespace.Item.Item.WithRunItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRunItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stream/{session_hash}/{run}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
