// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MobileDiffusion.Clients.SdForgeNeo.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.Upload_progress
{
    /// <summary>
    /// Builds and executes requests for operations under \upload_progress
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Upload_progressRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Upload_progressRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/upload_progress?upload_id={upload_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Upload_progressRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/upload_progress?upload_id={upload_id}", rawUrl)
        {
        }
        /// <summary>
        /// Get Upload Progress
        /// </summary>
        /// <returns>A <see cref="UntypedNode"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MobileDiffusion.Clients.SdForgeNeo.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<UntypedNode?> GetAsync(Action<RequestConfiguration<global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder.Upload_progressRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<UntypedNode> GetAsync(Action<RequestConfiguration<global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder.Upload_progressRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::MobileDiffusion.Clients.SdForgeNeo.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<UntypedNode>(requestInfo, UntypedNode.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Upload Progress
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder.Upload_progressRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder.Upload_progressRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get Upload Progress
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Upload_progressRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("upload_id")]
            public string? UploadId { get; set; }
#nullable restore
#else
            [QueryParameter("upload_id")]
            public string UploadId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Upload_progressRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MobileDiffusion.Clients.SdForgeNeo.Upload_progress.Upload_progressRequestBuilder.Upload_progressRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
