// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mogri.Clients.ComfyUi.Models
{
    /// <summary>
    /// Full job details including workflow and outputs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JobDetailResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Job creation timestamp (Unix timestamp in seconds)</summary>
        public long? CreateTime { get; set; }
        /// <summary>Detailed execution error information from ComfyUI</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mogri.Clients.ComfyUi.Models.ExecutionError? ExecutionError { get; set; }
#nullable restore
#else
        public global::Mogri.Clients.ComfyUi.Models.ExecutionError ExecutionError { get; set; }
#endif
        /// <summary>Node-level execution metadata (only for terminal states)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_meta? ExecutionMeta { get; set; }
#nullable restore
#else
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_meta ExecutionMeta { get; set; }
#endif
        /// <summary>ComfyUI execution status and timeline (only for terminal states)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_status? ExecutionStatus { get; set; }
#nullable restore
#else
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_status ExecutionStatus { get; set; }
#endif
        /// <summary>Unique job identifier</summary>
        public Guid? Id { get; set; }
        /// <summary>Full outputs object from ComfyUI (only for terminal states)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_outputs? Outputs { get; set; }
#nullable restore
#else
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_outputs Outputs { get; set; }
#endif
        /// <summary>Total number of output files (omitted for non-terminal states)</summary>
        public int? OutputsCount { get; set; }
        /// <summary>Primary preview output (only for terminal states)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_preview_output? PreviewOutput { get; set; }
#nullable restore
#else
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_preview_output PreviewOutput { get; set; }
#endif
        /// <summary>User-friendly job status</summary>
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_status? Status { get; set; }
        /// <summary>Last update timestamp (Unix timestamp in seconds)</summary>
        public long? UpdateTime { get; set; }
        /// <summary>Full ComfyUI workflow (10-100KB, omitted if not available)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_workflow? Workflow { get; set; }
#nullable restore
#else
        public global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_workflow Workflow { get; set; }
#endif
        /// <summary>UUID identifying the workflow graph definition</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Models.JobDetailResponse"/> and sets the default values.
        /// </summary>
        public JobDetailResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Models.JobDetailResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mogri.Clients.ComfyUi.Models.JobDetailResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mogri.Clients.ComfyUi.Models.JobDetailResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "create_time", n => { CreateTime = n.GetLongValue(); } },
                { "execution_error", n => { ExecutionError = n.GetObjectValue<global::Mogri.Clients.ComfyUi.Models.ExecutionError>(global::Mogri.Clients.ComfyUi.Models.ExecutionError.CreateFromDiscriminatorValue); } },
                { "execution_meta", n => { ExecutionMeta = n.GetObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_meta>(global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_meta.CreateFromDiscriminatorValue); } },
                { "execution_status", n => { ExecutionStatus = n.GetObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_status>(global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_status.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "outputs", n => { Outputs = n.GetObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_outputs>(global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_outputs.CreateFromDiscriminatorValue); } },
                { "outputs_count", n => { OutputsCount = n.GetIntValue(); } },
                { "preview_output", n => { PreviewOutput = n.GetObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_preview_output>(global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_preview_output.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_status>(); } },
                { "update_time", n => { UpdateTime = n.GetLongValue(); } },
                { "workflow", n => { Workflow = n.GetObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_workflow>(global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_workflow.CreateFromDiscriminatorValue); } },
                { "workflow_id", n => { WorkflowId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("create_time", CreateTime);
            writer.WriteObjectValue<global::Mogri.Clients.ComfyUi.Models.ExecutionError>("execution_error", ExecutionError);
            writer.WriteObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_meta>("execution_meta", ExecutionMeta);
            writer.WriteObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_execution_status>("execution_status", ExecutionStatus);
            writer.WriteGuidValue("id", Id);
            writer.WriteObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_outputs>("outputs", Outputs);
            writer.WriteIntValue("outputs_count", OutputsCount);
            writer.WriteObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_preview_output>("preview_output", PreviewOutput);
            writer.WriteEnumValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_status>("status", Status);
            writer.WriteLongValue("update_time", UpdateTime);
            writer.WriteObjectValue<global::Mogri.Clients.ComfyUi.Models.JobDetailResponse_workflow>("workflow", Workflow);
            writer.WriteStringValue("workflow_id", WorkflowId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
