// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mogri.Clients.ComfyUi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaginationInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether more items are available beyond this page</summary>
        public bool? HasMore { get; set; }
        /// <summary>Items per page</summary>
        public int? Limit { get; set; }
        /// <summary>Current offset (0-based)</summary>
        public int? Offset { get; set; }
        /// <summary>Total number of items matching filters</summary>
        public int? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Models.PaginationInfo"/> and sets the default values.
        /// </summary>
        public PaginationInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Models.PaginationInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mogri.Clients.ComfyUi.Models.PaginationInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mogri.Clients.ComfyUi.Models.PaginationInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "has_more", n => { HasMore = n.GetBoolValue(); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "offset", n => { Offset = n.GetIntValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("has_more", HasMore);
            writer.WriteIntValue("limit", Limit);
            writer.WriteIntValue("offset", Offset);
            writer.WriteIntValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
