// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mogri.Clients.ComfyUi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PromptRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Extra data to be associated with the prompt</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mogri.Clients.ComfyUi.Models.PromptRequest_extra_data? ExtraData { get; set; }
#nullable restore
#else
        public global::Mogri.Clients.ComfyUi.Models.PromptRequest_extra_data ExtraData { get; set; }
#endif
        /// <summary>If true, adds the prompt to the front of the queue.**Note:** Accepted for ComfyUI API compatibility but **ignored** in cloud.Cloud manages queue ordering internally based on job submission time and fair scheduling.</summary>
        public bool? Front { get; set; }
        /// <summary>Priority number for the queue (lower numbers have higher priority).**Note:** Accepted for ComfyUI API compatibility but **ignored** in cloud.Cloud uses its own queue management with per-user ordering and fair scheduling.</summary>
        public double? Number { get; set; }
        /// <summary>List of node names to execute</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PartialExecutionTargets { get; set; }
#nullable restore
#else
        public List<string> PartialExecutionTargets { get; set; }
#endif
        /// <summary>The workflow graph to execute</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mogri.Clients.ComfyUi.Models.PromptRequest_prompt? Prompt { get; set; }
#nullable restore
#else
        public global::Mogri.Clients.ComfyUi.Models.PromptRequest_prompt Prompt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Models.PromptRequest"/> and sets the default values.
        /// </summary>
        public PromptRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Models.PromptRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mogri.Clients.ComfyUi.Models.PromptRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mogri.Clients.ComfyUi.Models.PromptRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "extra_data", n => { ExtraData = n.GetObjectValue<global::Mogri.Clients.ComfyUi.Models.PromptRequest_extra_data>(global::Mogri.Clients.ComfyUi.Models.PromptRequest_extra_data.CreateFromDiscriminatorValue); } },
                { "front", n => { Front = n.GetBoolValue(); } },
                { "number", n => { Number = n.GetDoubleValue(); } },
                { "partial_execution_targets", n => { PartialExecutionTargets = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "prompt", n => { Prompt = n.GetObjectValue<global::Mogri.Clients.ComfyUi.Models.PromptRequest_prompt>(global::Mogri.Clients.ComfyUi.Models.PromptRequest_prompt.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Mogri.Clients.ComfyUi.Models.PromptRequest_extra_data>("extra_data", ExtraData);
            writer.WriteBoolValue("front", Front);
            writer.WriteDoubleValue("number", Number);
            writer.WriteCollectionOfPrimitiveValues<string>("partial_execution_targets", PartialExecutionTargets);
            writer.WriteObjectValue<global::Mogri.Clients.ComfyUi.Models.PromptRequest_prompt>("prompt", Prompt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
