// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Item;
using MobileDiffusion.Clients.ComfyUi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs
{
    /// <summary>
    /// Builds and executes requests for operations under \api\global_subgraphs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Global_subgraphsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MobileDiffusion.Clients.ComfyUi.api.global_subgraphs.item collection</summary>
        /// <param name="position">The unique identifier of the subgraph blueprint</param>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Item.Global_subgraphsItemRequestBuilder"/></returns>
        public global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Item.Global_subgraphsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Item.Global_subgraphsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Global_subgraphsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/global_subgraphs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Global_subgraphsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/global_subgraphs", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of globally available subgraph blueprints.These are pre-built workflow components that can be used as nodes.The data field contains a promise that resolves to the full subgraph JSON.
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsGetResponse?> GetAsGlobal_subgraphsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsGetResponse> GetAsGlobal_subgraphsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsGetResponse>(requestInfo, global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of globally available subgraph blueprints.These are pre-built workflow components that can be used as nodes.The data field contains a promise that resolves to the full subgraph JSON.
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsGlobal_subgraphsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsResponse>(requestInfo, global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of globally available subgraph blueprints.These are pre-built workflow components that can be used as nodes.The data field contains a promise that resolves to the full subgraph JSON.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MobileDiffusion.Clients.ComfyUi.Api.Global_subgraphs.Global_subgraphsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Global_subgraphsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
