// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Mogri.Clients.ComfyUi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata
{
    /// <summary>
    /// Builds and executes requests for operations under \api\assets\remote-metadata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RemoteMetadataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoteMetadataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/remote-metadata?url={url}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoteMetadataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/remote-metadata?url={url}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves metadata for an asset from a remote download URL without downloading the entire file.Supports various sources including CivitAI and other model repositories.Uses HEAD requests or API calls to fetch metadata efficiently.This endpoint is for previewing metadata before downloading, not for getting metadata of existing assets.
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Models.AssetMetadataResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mogri.Clients.ComfyUi.Models.AssetMetadataResponse?> GetAsync(Action<RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder.RemoteMetadataRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mogri.Clients.ComfyUi.Models.AssetMetadataResponse> GetAsync(Action<RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder.RemoteMetadataRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mogri.Clients.ComfyUi.Models.AssetMetadataResponse>(requestInfo, global::Mogri.Clients.ComfyUi.Models.AssetMetadataResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves metadata for an asset from a remote download URL without downloading the entire file.Supports various sources including CivitAI and other model repositories.Uses HEAD requests or API calls to fetch metadata efficiently.This endpoint is for previewing metadata before downloading, not for getting metadata of existing assets.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder.RemoteMetadataRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder.RemoteMetadataRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves metadata for an asset from a remote download URL without downloading the entire file.Supports various sources including CivitAI and other model repositories.Uses HEAD requests or API calls to fetch metadata efficiently.This endpoint is for previewing metadata before downloading, not for getting metadata of existing assets.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RemoteMetadataRequestBuilderGetQueryParameters 
        {
            /// <summary>Download URL to retrieve metadata from</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("url")]
            public string? Url { get; set; }
#nullable restore
#else
            [QueryParameter("url")]
            public string Url { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RemoteMetadataRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder.RemoteMetadataRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
