// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Mogri.Clients.ComfyUi.Api.Upload.Image;
using Mogri.Clients.ComfyUi.Api.Upload.Mask;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mogri.Clients.ComfyUi.Api.Upload
{
    /// <summary>
    /// Builds and executes requests for operations under \api\upload
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UploadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The image property</summary>
        public global::Mogri.Clients.ComfyUi.Api.Upload.Image.ImageRequestBuilder Image
        {
            get => new global::Mogri.Clients.ComfyUi.Api.Upload.Image.ImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mask property</summary>
        public global::Mogri.Clients.ComfyUi.Api.Upload.Mask.MaskRequestBuilder Mask
        {
            get => new global::Mogri.Clients.ComfyUi.Api.Upload.Mask.MaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Upload.UploadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UploadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/upload", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Upload.UploadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UploadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/upload", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
