// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MobileDiffusion.Clients.ComfyUi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash
{
    /// <summary>
    /// Builds and executes requests for operations under \api\assets\from-hash
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FromHashRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash.FromHashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FromHashRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/from-hash", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash.FromHashRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FromHashRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/from-hash", rawUrl)
        {
        }
        /// <summary>
        /// Creates a new asset reference using an existing hash from cloud storage.This avoids re-uploading file content when the underlying data already exists,which is useful for large files or when referencing well-known assets.The user provides their own metadata and tags for the new reference.
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Models.AssetCreated"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Models.AssetCreated?> PostAsync(global::MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash.FromHashPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Models.AssetCreated> PostAsync(global::MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash.FromHashPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MobileDiffusion.Clients.ComfyUi.Models.AssetCreated>(requestInfo, global::MobileDiffusion.Clients.ComfyUi.Models.AssetCreated.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new asset reference using an existing hash from cloud storage.This avoids re-uploading file content when the underlying data already exists,which is useful for large files or when referencing well-known assets.The user provides their own metadata and tags for the new reference.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash.FromHashPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash.FromHashPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash.FromHashRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash.FromHashRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MobileDiffusion.Clients.ComfyUi.Api.Assets.FromHash.FromHashRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FromHashRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
