// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MobileDiffusion.Clients.ComfyUi.Api.Workflow_templates
{
    /// <summary>
    /// Empty object for workflow templates
    /// </summary>
    [Obsolete("This class is obsolete. Use Workflow_templatesGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Workflow_templatesResponse : global::MobileDiffusion.Clients.ComfyUi.Api.Workflow_templates.Workflow_templatesGetResponse, IParsable
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Workflow_templates.Workflow_templatesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MobileDiffusion.Clients.ComfyUi.Api.Workflow_templates.Workflow_templatesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MobileDiffusion.Clients.ComfyUi.Api.Workflow_templates.Workflow_templatesResponse();
        }
    }
}
#pragma warning restore CS0618
