// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MobileDiffusion.Clients.ComfyUi.Models
{
    /// <summary>
    /// Job status information
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JobStatusResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The inference instance assigned to this job (if any)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignedInference { get; set; }
#nullable restore
#else
        public string AssignedInference { get; set; }
#endif
        /// <summary>When the job was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Error message if the job failed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>The job ID</summary>
        public Guid? Id { get; set; }
        /// <summary>When the job status was last changed</summary>
        public DateTimeOffset? LastStateUpdate { get; set; }
        /// <summary>Current job status</summary>
        public global::MobileDiffusion.Clients.ComfyUi.Models.JobStatusResponse_status? Status { get; set; }
        /// <summary>When the job was last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Models.JobStatusResponse"/> and sets the default values.
        /// </summary>
        public JobStatusResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Models.JobStatusResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MobileDiffusion.Clients.ComfyUi.Models.JobStatusResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MobileDiffusion.Clients.ComfyUi.Models.JobStatusResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assigned_inference", n => { AssignedInference = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "error_message", n => { ErrorMessage = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "last_state_update", n => { LastStateUpdate = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::MobileDiffusion.Clients.ComfyUi.Models.JobStatusResponse_status>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assigned_inference", AssignedInference);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("error_message", ErrorMessage);
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("last_state_update", LastStateUpdate);
            writer.WriteEnumValue<global::MobileDiffusion.Clients.ComfyUi.Models.JobStatusResponse_status>("status", Status);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
