// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MobileDiffusion.Clients.ComfyUi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemStatsResponse_system : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Command line arguments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Argv { get; set; }
#nullable restore
#else
        public List<string> Argv { get; set; }
#endif
        /// <summary>Cloud ingest service version (commit hash)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CloudVersion { get; set; }
#nullable restore
#else
        public string CloudVersion { get; set; }
#endif
        /// <summary>ComfyUI frontend version (commit hash or tag)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComfyuiFrontendVersion { get; set; }
#nullable restore
#else
        public string ComfyuiFrontendVersion { get; set; }
#endif
        /// <summary>ComfyUI version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComfyuiVersion { get; set; }
#nullable restore
#else
        public string ComfyuiVersion { get; set; }
#endif
        /// <summary>Whether using embedded Python</summary>
        public bool? EmbeddedPython { get; set; }
        /// <summary>Operating system</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Os { get; set; }
#nullable restore
#else
        public string Os { get; set; }
#endif
        /// <summary>Python version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PythonVersion { get; set; }
#nullable restore
#else
        public string PythonVersion { get; set; }
#endif
        /// <summary>PyTorch version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PytorchVersion { get; set; }
#nullable restore
#else
        public string PytorchVersion { get; set; }
#endif
        /// <summary>Free RAM in bytes</summary>
        public double? RamFree { get; set; }
        /// <summary>Total RAM in bytes</summary>
        public double? RamTotal { get; set; }
        /// <summary>Workflow templates version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowTemplatesVersion { get; set; }
#nullable restore
#else
        public string WorkflowTemplatesVersion { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Models.SystemStatsResponse_system"/> and sets the default values.
        /// </summary>
        public SystemStatsResponse_system()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Models.SystemStatsResponse_system"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MobileDiffusion.Clients.ComfyUi.Models.SystemStatsResponse_system CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MobileDiffusion.Clients.ComfyUi.Models.SystemStatsResponse_system();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "argv", n => { Argv = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "cloud_version", n => { CloudVersion = n.GetStringValue(); } },
                { "comfyui_frontend_version", n => { ComfyuiFrontendVersion = n.GetStringValue(); } },
                { "comfyui_version", n => { ComfyuiVersion = n.GetStringValue(); } },
                { "embedded_python", n => { EmbeddedPython = n.GetBoolValue(); } },
                { "os", n => { Os = n.GetStringValue(); } },
                { "python_version", n => { PythonVersion = n.GetStringValue(); } },
                { "pytorch_version", n => { PytorchVersion = n.GetStringValue(); } },
                { "ram_free", n => { RamFree = n.GetDoubleValue(); } },
                { "ram_total", n => { RamTotal = n.GetDoubleValue(); } },
                { "workflow_templates_version", n => { WorkflowTemplatesVersion = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("argv", Argv);
            writer.WriteStringValue("cloud_version", CloudVersion);
            writer.WriteStringValue("comfyui_frontend_version", ComfyuiFrontendVersion);
            writer.WriteStringValue("comfyui_version", ComfyuiVersion);
            writer.WriteBoolValue("embedded_python", EmbeddedPython);
            writer.WriteStringValue("os", Os);
            writer.WriteStringValue("python_version", PythonVersion);
            writer.WriteStringValue("pytorch_version", PytorchVersion);
            writer.WriteDoubleValue("ram_free", RamFree);
            writer.WriteDoubleValue("ram_total", RamTotal);
            writer.WriteStringValue("workflow_templates_version", WorkflowTemplatesVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
