// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Mogri.Clients.ComfyUi.Api.Assets.Tags.Refine;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mogri.Clients.ComfyUi.Api.Assets.Tags
{
    /// <summary>
    /// Builds and executes requests for operations under \api\assets\tags
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TagsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The refine property</summary>
        public global::Mogri.Clients.ComfyUi.Api.Assets.Tags.Refine.RefineRequestBuilder Refine
        {
            get => new global::Mogri.Clients.ComfyUi.Api.Assets.Tags.Refine.RefineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/tags", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/tags", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
