// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MobileDiffusion.Clients.SdForgeNeo.Sdapi.V1;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.Sdapi
{
    /// <summary>
    /// Builds and executes requests for operations under \sdapi
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SdapiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The v1 property</summary>
        public global::MobileDiffusion.Clients.SdForgeNeo.Sdapi.V1.V1RequestBuilder V1
        {
            get => new global::MobileDiffusion.Clients.SdForgeNeo.Sdapi.V1.V1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Sdapi.SdapiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SdapiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sdapi", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Sdapi.SdapiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SdapiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sdapi", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
