// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mogri.Clients.SdForgeNeo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExtrasBatchImagesRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Sets the visibility of CodeFormer, values should be between 0 and 1.</summary>
        public double? CodeformerVisibility { get; set; }
        /// <summary>Sets the weight of CodeFormer, values should be between 0 and 1.</summary>
        public double? CodeformerWeight { get; set; }
        /// <summary>Sets the visibility of secondary upscaler, values should be between 0 and 1.</summary>
        public double? ExtrasUpscaler2Visibility { get; set; }
        /// <summary>Sets the visibility of GFPGAN, values should be between 0 and 1.</summary>
        public double? GfpganVisibility { get; set; }
        /// <summary>List of images to work on. Must be Base64 strings</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Mogri.Clients.SdForgeNeo.Models.FileData>? ImageList { get; set; }
#nullable restore
#else
        public List<global::Mogri.Clients.SdForgeNeo.Models.FileData> ImageList { get; set; }
#endif
        /// <summary>Sets the resize mode: 0 to upscale by upscaling_resize amount, 1 to upscale up to upscaling_resize_h x upscaling_resize_w.</summary>
        public int? ResizeMode { get; set; }
        /// <summary>Should the backend return the generated image?</summary>
        public bool? ShowExtrasResults { get; set; }
        /// <summary>Should the upscaler run before restoring faces?</summary>
        public bool? UpscaleFirst { get; set; }
        /// <summary>The name of the main upscaler to use, it has to be one of this list: </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Upscaler1 { get; set; }
#nullable restore
#else
        public string Upscaler1 { get; set; }
#endif
        /// <summary>The name of the secondary upscaler to use, it has to be one of this list: </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Upscaler2 { get; set; }
#nullable restore
#else
        public string Upscaler2 { get; set; }
#endif
        /// <summary>Should the upscaler crop the image to fit in the chosen size?</summary>
        public bool? UpscalingCrop { get; set; }
        /// <summary>By how much to upscale the image, only used when resize_mode=0.</summary>
        public double? UpscalingResize { get; set; }
        /// <summary>Target height for the upscaler to hit. Only used when resize_mode=1.</summary>
        public int? UpscalingResizeH { get; set; }
        /// <summary>Target width for the upscaler to hit. Only used when resize_mode=1.</summary>
        public int? UpscalingResizeW { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.SdForgeNeo.Models.ExtrasBatchImagesRequest"/> and sets the default values.
        /// </summary>
        public ExtrasBatchImagesRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Upscaler1 = "None";
            Upscaler2 = "None";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.SdForgeNeo.Models.ExtrasBatchImagesRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mogri.Clients.SdForgeNeo.Models.ExtrasBatchImagesRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mogri.Clients.SdForgeNeo.Models.ExtrasBatchImagesRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "codeformer_visibility", n => { CodeformerVisibility = n.GetDoubleValue(); } },
                { "codeformer_weight", n => { CodeformerWeight = n.GetDoubleValue(); } },
                { "extras_upscaler_2_visibility", n => { ExtrasUpscaler2Visibility = n.GetDoubleValue(); } },
                { "gfpgan_visibility", n => { GfpganVisibility = n.GetDoubleValue(); } },
                { "imageList", n => { ImageList = n.GetCollectionOfObjectValues<global::Mogri.Clients.SdForgeNeo.Models.FileData>(global::Mogri.Clients.SdForgeNeo.Models.FileData.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resize_mode", n => { ResizeMode = n.GetIntValue(); } },
                { "show_extras_results", n => { ShowExtrasResults = n.GetBoolValue(); } },
                { "upscale_first", n => { UpscaleFirst = n.GetBoolValue(); } },
                { "upscaler_1", n => { Upscaler1 = n.GetStringValue(); } },
                { "upscaler_2", n => { Upscaler2 = n.GetStringValue(); } },
                { "upscaling_crop", n => { UpscalingCrop = n.GetBoolValue(); } },
                { "upscaling_resize", n => { UpscalingResize = n.GetDoubleValue(); } },
                { "upscaling_resize_h", n => { UpscalingResizeH = n.GetIntValue(); } },
                { "upscaling_resize_w", n => { UpscalingResizeW = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("codeformer_visibility", CodeformerVisibility);
            writer.WriteDoubleValue("codeformer_weight", CodeformerWeight);
            writer.WriteDoubleValue("extras_upscaler_2_visibility", ExtrasUpscaler2Visibility);
            writer.WriteDoubleValue("gfpgan_visibility", GfpganVisibility);
            writer.WriteCollectionOfObjectValues<global::Mogri.Clients.SdForgeNeo.Models.FileData>("imageList", ImageList);
            writer.WriteIntValue("resize_mode", ResizeMode);
            writer.WriteBoolValue("show_extras_results", ShowExtrasResults);
            writer.WriteBoolValue("upscale_first", UpscaleFirst);
            writer.WriteStringValue("upscaler_1", Upscaler1);
            writer.WriteStringValue("upscaler_2", Upscaler2);
            writer.WriteBoolValue("upscaling_crop", UpscalingCrop);
            writer.WriteDoubleValue("upscaling_resize", UpscalingResize);
            writer.WriteIntValue("upscaling_resize_h", UpscalingResizeH);
            writer.WriteIntValue("upscaling_resize_w", UpscalingResizeW);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
