// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mogri.Clients.SdForgeNeo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Modules__api__models__ProgressResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current image in base64 format. opts.show_progress_every_n_steps is required for this to work.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentImage { get; set; }
#nullable restore
#else
        public string CurrentImage { get; set; }
#endif
        /// <summary>The eta_relative property</summary>
        public double? EtaRelative { get; set; }
        /// <summary>The progress with a range of 0 to 1</summary>
        public double? Progress { get; set; }
        /// <summary>The current state snapshot</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mogri.Clients.SdForgeNeo.Models.Modules__api__models__ProgressResponse_state? State { get; set; }
#nullable restore
#else
        public global::Mogri.Clients.SdForgeNeo.Models.Modules__api__models__ProgressResponse_state State { get; set; }
#endif
        /// <summary>Info text used by WebUI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Textinfo { get; set; }
#nullable restore
#else
        public string Textinfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.SdForgeNeo.Models.Modules__api__models__ProgressResponse"/> and sets the default values.
        /// </summary>
        public Modules__api__models__ProgressResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.SdForgeNeo.Models.Modules__api__models__ProgressResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mogri.Clients.SdForgeNeo.Models.Modules__api__models__ProgressResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mogri.Clients.SdForgeNeo.Models.Modules__api__models__ProgressResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current_image", n => { CurrentImage = n.GetStringValue(); } },
                { "eta_relative", n => { EtaRelative = n.GetDoubleValue(); } },
                { "progress", n => { Progress = n.GetDoubleValue(); } },
                { "state", n => { State = n.GetObjectValue<global::Mogri.Clients.SdForgeNeo.Models.Modules__api__models__ProgressResponse_state>(global::Mogri.Clients.SdForgeNeo.Models.Modules__api__models__ProgressResponse_state.CreateFromDiscriminatorValue); } },
                { "textinfo", n => { Textinfo = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("current_image", CurrentImage);
            writer.WriteDoubleValue("eta_relative", EtaRelative);
            writer.WriteDoubleValue("progress", Progress);
            writer.WriteObjectValue<global::Mogri.Clients.SdForgeNeo.Models.Modules__api__models__ProgressResponse_state>("state", State);
            writer.WriteStringValue("textinfo", Textinfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
