// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Mogri.Clients.SdForgeNeo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Sage_quantization_backend
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cuda")]
        #pragma warning disable CS1591
        Cuda,
        #pragma warning restore CS1591
        [EnumMember(Value = "triton")]
        #pragma warning disable CS1591
        Triton,
        #pragma warning restore CS1591
    }
}
