// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Mogri.Clients.SdForgeNeo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SageAttentionFuncs
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "fp16_triton")]
        #pragma warning disable CS1591
        Fp16_triton,
        #pragma warning restore CS1591
        [EnumMember(Value = "fp16_cuda")]
        #pragma warning disable CS1591
        Fp16_cuda,
        #pragma warning restore CS1591
        [EnumMember(Value = "fp8_cuda")]
        #pragma warning disable CS1591
        Fp8_cuda,
        #pragma warning restore CS1591
    }
}
