// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Mogri.Clients.ComfyUi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mogri.Clients.ComfyUi.Api.Assets.Download
{
    /// <summary>
    /// Builds and executes requests for operations under \api\assets\download
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/download", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets/download", rawUrl)
        {
        }
        /// <summary>
        /// Initiates a background download job for large files from Huggingface or Civitai.If the file already exists in storage, the asset record is created immediately and returned (200 OK).If the file doesn&apos;t exist, a background task is created and the task ID is returned (202 Accepted).The frontend can track progress using GET /api/tasks/{task_id}.
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Models.AssetCreated"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mogri.Clients.ComfyUi.Models.AssetCreated?> PostAsync(global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mogri.Clients.ComfyUi.Models.AssetCreated> PostAsync(global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mogri.Clients.ComfyUi.Models.AssetCreated>(requestInfo, global::Mogri.Clients.ComfyUi.Models.AssetCreated.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiates a background download job for large files from Huggingface or Civitai.If the file already exists in storage, the asset record is created immediately and returned (200 OK).If the file doesn&apos;t exist, a background task is created and the task ID is returned (202 Accepted).The frontend can track progress using GET /api/tasks/{task_id}.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DownloadRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
