// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Mogri.Clients.SdForgeNeo.Custom_component.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mogri.Clients.SdForgeNeo.Custom_component.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \custom_component\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Custom_componentItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Mogri.Clients.SdForgeNeo.custom_component.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Mogri.Clients.SdForgeNeo.Custom_component.Item.Item.WithTypeItemRequestBuilder"/></returns>
        public global::Mogri.Clients.SdForgeNeo.Custom_component.Item.Item.WithTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("type", position);
                return new global::Mogri.Clients.SdForgeNeo.Custom_component.Item.Item.WithTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.SdForgeNeo.Custom_component.Item.Custom_componentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_componentItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_component/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.SdForgeNeo.Custom_component.Item.Custom_componentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_componentItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_component/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
