// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Mogri.Clients.ComfyUi.Api.Assets.Download;
using Mogri.Clients.ComfyUi.Api.Assets.FromHash;
using Mogri.Clients.ComfyUi.Api.Assets.Hash;
using Mogri.Clients.ComfyUi.Api.Assets.Item;
using Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata;
using Mogri.Clients.ComfyUi.Api.Assets.Tags;
using Mogri.Clients.ComfyUi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mogri.Clients.ComfyUi.Api.Assets
{
    /// <summary>
    /// Builds and executes requests for operations under \api\assets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The download property</summary>
        public global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadRequestBuilder Download
        {
            get => new global::Mogri.Clients.ComfyUi.Api.Assets.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fromHash property</summary>
        public global::Mogri.Clients.ComfyUi.Api.Assets.FromHash.FromHashRequestBuilder FromHash
        {
            get => new global::Mogri.Clients.ComfyUi.Api.Assets.FromHash.FromHashRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hash property</summary>
        public global::Mogri.Clients.ComfyUi.Api.Assets.Hash.HashRequestBuilder Hash
        {
            get => new global::Mogri.Clients.ComfyUi.Api.Assets.Hash.HashRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remoteMetadata property</summary>
        public global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder RemoteMetadata
        {
            get => new global::Mogri.Clients.ComfyUi.Api.Assets.RemoteMetadata.RemoteMetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Mogri.Clients.ComfyUi.Api.Assets.Tags.TagsRequestBuilder Tags
        {
            get => new global::Mogri.Clients.ComfyUi.Api.Assets.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Mogri.Clients.ComfyUi.api.assets.item collection</summary>
        /// <param name="position">Asset ID</param>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Item.AssetsItemRequestBuilder"/></returns>
        public global::Mogri.Clients.ComfyUi.Api.Assets.Item.AssetsItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Mogri.Clients.ComfyUi.Api.Assets.Item.AssetsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Mogri.Clients.ComfyUi.api.assets.item collection</summary>
        /// <param name="position">Asset ID</param>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.Item.AssetsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Mogri.Clients.ComfyUi.Api.Assets.Item.AssetsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Mogri.Clients.ComfyUi.Api.Assets.Item.AssetsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets{?exclude_tags,include_public*,include_tags,limit*,metadata_filter*,name_contains*,offset*,order*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/assets{?exclude_tags,include_public*,include_tags,limit*,metadata_filter*,name_contains*,offset*,order*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a paginated list of assets belonging to the authenticated user.Supports filtering by tags, name, metadata, and sorting options.
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Models.ListAssetsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mogri.Clients.ComfyUi.Models.ListAssetsResponse?> GetAsync(Action<RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder.AssetsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mogri.Clients.ComfyUi.Models.ListAssetsResponse> GetAsync(Action<RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder.AssetsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mogri.Clients.ComfyUi.Models.ListAssetsResponse>(requestInfo, global::Mogri.Clients.ComfyUi.Models.ListAssetsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Uploads a new asset to the system with associated metadata.Supports two upload methods:1. Direct file upload (multipart/form-data)2. URL-based upload (application/json with source: &quot;url&quot;)If an asset with the same hash already exists, returns the existing asset.
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Models.AssetCreated"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 413 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 415 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::Mogri.Clients.ComfyUi.Models.ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mogri.Clients.ComfyUi.Models.AssetCreated?> PostAsync(global::Mogri.Clients.ComfyUi.Api.Assets.AssetsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mogri.Clients.ComfyUi.Models.AssetCreated> PostAsync(global::Mogri.Clients.ComfyUi.Api.Assets.AssetsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "413", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "415", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Mogri.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mogri.Clients.ComfyUi.Models.AssetCreated>(requestInfo, global::Mogri.Clients.ComfyUi.Models.AssetCreated.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a paginated list of assets belonging to the authenticated user.Supports filtering by tags, name, metadata, and sorting options.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder.AssetsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder.AssetsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Uploads a new asset to the system with associated metadata.Supports two upload methods:1. Direct file upload (multipart/form-data)2. URL-based upload (application/json with source: &quot;url&quot;)If an asset with the same hash already exists, returns the existing asset.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Mogri.Clients.ComfyUi.Api.Assets.AssetsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Mogri.Clients.ComfyUi.Api.Assets.AssetsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "multipart/form-data", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a paginated list of assets belonging to the authenticated user.Supports filtering by tags, name, metadata, and sorting options.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AssetsRequestBuilderGetQueryParameters 
        {
            /// <summary>Exclude assets that have ANY of these tags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("exclude_tags")]
            public string[]? ExcludeTags { get; set; }
#nullable restore
#else
            [QueryParameter("exclude_tags")]
            public string[] ExcludeTags { get; set; }
#endif
            /// <summary>Whether to include public/shared assets in results</summary>
            [QueryParameter("include_public")]
            public bool? IncludePublic { get; set; }
            /// <summary>Filter assets that have ALL of these tags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include_tags")]
            public string[]? IncludeTags { get; set; }
#nullable restore
#else
            [QueryParameter("include_tags")]
            public string[] IncludeTags { get; set; }
#endif
            /// <summary>Maximum number of assets to return (1-500)</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>JSON object for filtering by metadata fields</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("metadata_filter")]
            public string? MetadataFilter { get; set; }
#nullable restore
#else
            [QueryParameter("metadata_filter")]
            public string MetadataFilter { get; set; }
#endif
            /// <summary>Filter assets where name contains this substring (case-insensitive)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name_contains")]
            public string? NameContains { get; set; }
#nullable restore
#else
            [QueryParameter("name_contains")]
            public string NameContains { get; set; }
#endif
            /// <summary>Number of assets to skip for pagination</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>Sort order</summary>
            [Obsolete("This property is deprecated, use OrderAsGetOrderQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>Sort order</summary>
            [QueryParameter("order")]
            public global::Mogri.Clients.ComfyUi.Api.Assets.GetOrderQueryParameterType? OrderAsGetOrderQueryParameterType { get; set; }
            /// <summary>Field to sort by</summary>
            [Obsolete("This property is deprecated, use SortAsGetSortQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            /// <summary>Field to sort by</summary>
            [QueryParameter("sort")]
            public global::Mogri.Clients.ComfyUi.Api.Assets.GetSortQueryParameterType? SortAsGetSortQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AssetsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Mogri.Clients.ComfyUi.Api.Assets.AssetsRequestBuilder.AssetsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AssetsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
