// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MobileDiffusion.Clients.SdForgeNeo.Queue.Data;
using MobileDiffusion.Clients.SdForgeNeo.Queue.Join;
using MobileDiffusion.Clients.SdForgeNeo.Queue.Status;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.Queue
{
    /// <summary>
    /// Builds and executes requests for operations under \queue
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueueRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The data property</summary>
        public global::MobileDiffusion.Clients.SdForgeNeo.Queue.Data.DataRequestBuilder Data
        {
            get => new global::MobileDiffusion.Clients.SdForgeNeo.Queue.Data.DataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The join property</summary>
        public global::MobileDiffusion.Clients.SdForgeNeo.Queue.Join.JoinRequestBuilder Join
        {
            get => new global::MobileDiffusion.Clients.SdForgeNeo.Queue.Join.JoinRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::MobileDiffusion.Clients.SdForgeNeo.Queue.Status.StatusRequestBuilder Status
        {
            get => new global::MobileDiffusion.Clients.SdForgeNeo.Queue.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Queue.QueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueueRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/queue", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Queue.QueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueueRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/queue", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
