// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MobileDiffusion.Clients.SdForgeNeo.Heartbeat.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.Heartbeat
{
    /// <summary>
    /// Builds and executes requests for operations under \heartbeat
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HeartbeatRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MobileDiffusion.Clients.SdForgeNeo.heartbeat.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Heartbeat.Item.WithSession_hashItemRequestBuilder"/></returns>
        public global::MobileDiffusion.Clients.SdForgeNeo.Heartbeat.Item.WithSession_hashItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("session_hash", position);
                return new global::MobileDiffusion.Clients.SdForgeNeo.Heartbeat.Item.WithSession_hashItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Heartbeat.HeartbeatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HeartbeatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/heartbeat", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Heartbeat.HeartbeatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HeartbeatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/heartbeat", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
