// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MobileDiffusion.Clients.ComfyUi.Api.Job.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MobileDiffusion.Clients.ComfyUi.Api.Job
{
    /// <summary>
    /// Builds and executes requests for operations under \api\job
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JobRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MobileDiffusion.Clients.ComfyUi.api.job.item collection</summary>
        /// <param name="position">The unique ID of the job</param>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Job.Item.WithJob_ItemRequestBuilder"/></returns>
        public global::MobileDiffusion.Clients.ComfyUi.Api.Job.Item.WithJob_ItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("job_id", position);
                return new global::MobileDiffusion.Clients.ComfyUi.Api.Job.Item.WithJob_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the MobileDiffusion.Clients.ComfyUi.api.job.item collection</summary>
        /// <param name="position">The unique ID of the job</param>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Job.Item.WithJob_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::MobileDiffusion.Clients.ComfyUi.Api.Job.Item.WithJob_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("job_id", position);
                return new global::MobileDiffusion.Clients.ComfyUi.Api.Job.Item.WithJob_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Job.JobRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JobRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/job", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Job.JobRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JobRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/job", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
