// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MobileDiffusion.Clients.ComfyUi.Api.Assets.Download
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DownloadPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional preview asset ID to associate with the downloaded asset</summary>
        public Guid? PreviewId { get; set; }
        /// <summary>URL of the file to download (must be from huggingface.co or civitai.com)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceUrl { get; set; }
#nullable restore
#else
        public string SourceUrl { get; set; }
#endif
        /// <summary>Optional tags for the asset (e.g., [&quot;model&quot;, &quot;checkpoint&quot;])</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>Optional user-defined metadata to attach to the asset</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MobileDiffusion.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody_user_metadata? UserMetadata { get; set; }
#nullable restore
#else
        public global::MobileDiffusion.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody_user_metadata UserMetadata { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody"/> and sets the default values.
        /// </summary>
        public DownloadPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MobileDiffusion.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MobileDiffusion.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "preview_id", n => { PreviewId = n.GetGuidValue(); } },
                { "source_url", n => { SourceUrl = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "user_metadata", n => { UserMetadata = n.GetObjectValue<global::MobileDiffusion.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody_user_metadata>(global::MobileDiffusion.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody_user_metadata.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("preview_id", PreviewId);
            writer.WriteStringValue("source_url", SourceUrl);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteObjectValue<global::MobileDiffusion.Clients.ComfyUi.Api.Assets.Download.DownloadPostRequestBody_user_metadata>("user_metadata", UserMetadata);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
