// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Mogri.Clients.ComfyUi.Api.Jobs
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSort_byQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "create_time")]
        #pragma warning disable CS1591
        Create_time,
        #pragma warning restore CS1591
        [EnumMember(Value = "execution_time")]
        #pragma warning disable CS1591
        Execution_time,
        #pragma warning restore CS1591
    }
}
