// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MobileDiffusion.Clients.ComfyUi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers
{
    /// <summary>
    /// Builds and executes requests for operations under \api\files\mask-layers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MaskLayersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MaskLayersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/files/mask-layers?filename={filename}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MaskLayersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/files/mask-layers?filename={filename}", rawUrl)
        {
        }
        /// <summary>
        /// Given a mask file (any of the 4 layers), returns all related mask layer files.This is used by the mask editor to load the paint, mask, and painted layerswhen reopening a previously edited mask.
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersGetResponse?> GetAsMaskLayersGetResponseAsync(Action<RequestConfiguration<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder.MaskLayersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersGetResponse> GetAsMaskLayersGetResponseAsync(Action<RequestConfiguration<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder.MaskLayersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersGetResponse>(requestInfo, global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Given a mask file (any of the 4 layers), returns all related mask layer files.This is used by the mask editor to load the paint, mask, and painted layerswhen reopening a previously edited mask.
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse">When receiving a 404 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsMaskLayersGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersResponse?> GetAsync(Action<RequestConfiguration<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder.MaskLayersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersResponse> GetAsync(Action<RequestConfiguration<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder.MaskLayersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::MobileDiffusion.Clients.ComfyUi.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersResponse>(requestInfo, global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Given a mask file (any of the 4 layers), returns all related mask layer files.This is used by the mask editor to load the paint, mask, and painted layerswhen reopening a previously edited mask.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder.MaskLayersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder.MaskLayersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Given a mask file (any of the 4 layers), returns all related mask layer files.This is used by the mask editor to load the paint, mask, and painted layerswhen reopening a previously edited mask.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MaskLayersRequestBuilderGetQueryParameters 
        {
            /// <summary>Hash filename of any mask layer file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filename")]
            public string? Filename { get; set; }
#nullable restore
#else
            [QueryParameter("filename")]
            public string Filename { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MaskLayersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MobileDiffusion.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder.MaskLayersRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
