// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Mogri.Clients.ComfyUi.Api.Files.MaskLayers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mogri.Clients.ComfyUi.Api.Files
{
    /// <summary>
    /// Builds and executes requests for operations under \api\files
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The maskLayers property</summary>
        public global::Mogri.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder MaskLayers
        {
            get => new global::Mogri.Clients.ComfyUi.Api.Files.MaskLayers.MaskLayersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/files", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mogri.Clients.ComfyUi.Api.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/files", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
