// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EstimationMessage : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The event_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventId { get; set; }
#nullable restore
#else
        public string EventId { get; set; }
#endif
        /// <summary>The msg property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Msg { get; set; }
#nullable restore
#else
        public string Msg { get; set; }
#endif
        /// <summary>The queue_size property</summary>
        public int? QueueSize { get; set; }
        /// <summary>The rank property</summary>
        public int? Rank { get; set; }
        /// <summary>The rank_eta property</summary>
        public double? RankEta { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Models.EstimationMessage"/> and sets the default values.
        /// </summary>
        public EstimationMessage()
        {
            AdditionalData = new Dictionary<string, object>();
            Msg = "estimation";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Models.EstimationMessage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MobileDiffusion.Clients.SdForgeNeo.Models.EstimationMessage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MobileDiffusion.Clients.SdForgeNeo.Models.EstimationMessage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "event_id", n => { EventId = n.GetStringValue(); } },
                { "msg", n => { Msg = n.GetStringValue(); } },
                { "queue_size", n => { QueueSize = n.GetIntValue(); } },
                { "rank", n => { Rank = n.GetIntValue(); } },
                { "rank_eta", n => { RankEta = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("event_id", EventId);
            writer.WriteStringValue("msg", Msg);
            writer.WriteIntValue("queue_size", QueueSize);
            writer.WriteIntValue("rank", Rank);
            writer.WriteDoubleValue("rank_eta", RankEta);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
