// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Flags : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Administrator rights</summary>
        public bool? Administrator { get; set; }
        /// <summary>show the &quot;sampler parameters&quot; advanced settings</summary>
        public bool? AdvSamplers { get; set; }
        /// <summary>show non-UI parameters in X/Y/Z Plot options</summary>
        public bool? AdvXyz { get; set; }
        /// <summary>The all_in_fp16 property</summary>
        public bool? AllInFp16 { get; set; }
        /// <summary>The all_in_fp32 property</summary>
        public bool? AllInFp32 { get; set; }
        /// <summary>The always_cpu property</summary>
        public bool? AlwaysCpu { get; set; }
        /// <summary>The always_gpu property</summary>
        public bool? AlwaysGpu { get; set; }
        /// <summary>The always_high_vram property</summary>
        public bool? AlwaysHighVram { get; set; }
        /// <summary>The always_low_vram property</summary>
        public bool? AlwaysLowVram { get; set; }
        /// <summary>The always_normal_vram property</summary>
        public bool? AlwaysNormalVram { get; set; }
        /// <summary>The always_no_vram property</summary>
        public bool? AlwaysNoVram { get; set; }
        /// <summary>The always_offload_from_vram property</summary>
        public bool? AlwaysOffloadFromVram { get; set; }
        /// <summary>use api=True to launch the API together with the webui (use --nowebui instead for only the API)</summary>
        public bool? Api { get; set; }
        /// <summary>Set authentication for API like &quot;username:password&quot;; or comma-delimit multiple like &quot;u1:p1,u2:p2,u3:p3&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiAuth { get; set; }
#nullable restore
#else
        public string ApiAuth { get; set; }
#endif
        /// <summary>use api-log=True to enable logging of all API requests</summary>
        public bool? ApiLog { get; set; }
        /// <summary>enable server stop/restart/kill via api</summary>
        public bool? ApiServerStop { get; set; }
        /// <summary>The attention_pytorch property</summary>
        public bool? AttentionPytorch { get; set; }
        /// <summary>open the webui URL in the system&apos;s default browser upon launch</summary>
        public bool? Autolaunch { get; set; }
        /// <summary>path to checkpoint of stable diffusion model; if specified, this checkpoint will be added to the list of checkpoints and loaded</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ckpt { get; set; }
#nullable restore
#else
        public string Ckpt { get; set; }
#endif
        /// <summary>Path to directory with stable diffusion checkpoints</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CkptDir { get; set; }
#nullable restore
#else
        public string CkptDir { get; set; }
#endif
        /// <summary>The clip_in_fp16 property</summary>
        public bool? ClipInFp16 { get; set; }
        /// <summary>The clip_in_fp32 property</summary>
        public bool? ClipInFp32 { get; set; }
        /// <summary>The clip_in_fp8_e4m3fn property</summary>
        public bool? ClipInFp8E4m3fn { get; set; }
        /// <summary>The clip_in_fp8_e5m2 property</summary>
        public bool? ClipInFp8E5m2 { get; set; }
        /// <summary>The clip_in_gpu property</summary>
        public bool? ClipInGpu { get; set; }
        /// <summary>Path to directory with codeformer model file(s).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodeformerModelsPath { get; set; }
#nullable restore
#else
        public string CodeformerModelsPath { get; set; }
#endif
        /// <summary>path to config which constructs model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Config { get; set; }
#nullable restore
#else
        public string Config { get; set; }
#endif
        /// <summary>Path to directory with ControlNet models</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ControlnetDir { get; set; }
#nullable restore
#else
        public string ControlnetDir { get; set; }
#endif
        /// <summary>Set the log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ControlnetLoglevel { get; set; }
#nullable restore
#else
        public string ControlnetLoglevel { get; set; }
#endif
        /// <summary>Path to directory with annotator model directories</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ControlnetPreprocessorModelsDir { get; set; }
#nullable restore
#else
        public string ControlnetPreprocessorModelsDir { get; set; }
#endif
        /// <summary>Allowed CORS origin(s) in the form of a comma-separated list (no spaces)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CorsAllowOrigins { get; set; }
#nullable restore
#else
        public string CorsAllowOrigins { get; set; }
#endif
        /// <summary>Allowed CORS origin(s) in the form of a single regular expression</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CorsAllowOriginsRegex { get; set; }
#nullable restore
#else
        public string CorsAllowOriginsRegex { get; set; }
#endif
        /// <summary>The cuda_malloc property</summary>
        public bool? CudaMalloc { get; set; }
        /// <summary>The cuda_stream property</summary>
        public bool? CudaStream { get; set; }
        /// <summary>base path where all user data is stored</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataDir { get; set; }
#nullable restore
#else
        public string DataDir { get; set; }
#endif
        /// <summary>Select the default CUDA device to use (export CUDA_VISIBLE_DEVICES=0,1,etc might be needed before)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceId { get; set; }
#nullable restore
#else
        public string DeviceId { get; set; }
#endif
        /// <summary>The directml property</summary>
        public bool? Directml { get; set; }
        /// <summary>prevent all extensions from running regardless of any other settings</summary>
        public bool? DisableAllExtensions { get; set; }
        /// <summary>The disable_attention_upcast property</summary>
        public bool? DisableAttentionUpcast { get; set; }
        /// <summary>do not output progressbars to console</summary>
        public bool? DisableConsoleProgressbars { get; set; }
        /// <summary>prevent all extensions except built-in from running regardless of any other settings</summary>
        public bool? DisableExtraExtensions { get; set; }
        /// <summary>The disable_flash property</summary>
        public bool? DisableFlash { get; set; }
        /// <summary>The disable_ipex_hijack property</summary>
        public bool? DisableIpexHijack { get; set; }
        /// <summary>do not check if produced images/latent spaces have nans; useful for running without a checkpoint in CI</summary>
        public bool? DisableNanCheck { get; set; }
        /// <summary>does absolutely nothing</summary>
        public bool? DisableSafeUnpickle { get; set; }
        /// <summary>The disable_sage property</summary>
        public bool? DisableSage { get; set; }
        /// <summary>When passed, enables the use of self-signed certificates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisableTlsVerify { get; set; }
#nullable restore
#else
        public string DisableTlsVerify { get; set; }
#endif
        /// <summary>The disable_xformers property</summary>
        public bool? DisableXformers { get; set; }
        /// <summary>launch.py argument: dump limited sysinfo file (without information about extensions, options) to disk and quit</summary>
        public bool? DumpSysinfo { get; set; }
        /// <summary>textual inversion directory</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmbeddingsDir { get; set; }
#nullable restore
#else
        public string EmbeddingsDir { get; set; }
#endif
        /// <summary>enable extensions tab regardless of other options</summary>
        public bool? EnableInsecureExtensionAccess { get; set; }
        /// <summary>Path to directory with ESRGAN model file(s).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EsrganModelsPath { get; set; }
#nullable restore
#else
        public string EsrganModelsPath { get; set; }
#endif
        /// <summary>==SUPPRESS==</summary>
        public bool? F { get; set; }
        /// <summary>The fast_fp16 property</summary>
        public bool? FastFp16 { get; set; }
        /// <summary>install flash_attn</summary>
        public bool? Flash { get; set; }
        /// <summary>Look for models in an existing A1111 checkout&apos;s path</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForgeRefA1111Home { get; set; }
#nullable restore
#else
        public string ForgeRefA1111Home { get; set; }
#endif
        /// <summary>refresh rate for threads</summary>
        public int? Fps { get; set; }
        /// <summary>disable editing of all settings globally</summary>
        public bool? FreezeSettings { get; set; }
        /// <summary>disable editing settings in specific sections of the settings page by specifying a comma-delimited list such like &quot;saving-images,upscaling&quot;. The list of setting names can be found in the modules/shared_options.py file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FreezeSettingsInSections { get; set; }
#nullable restore
#else
        public string FreezeSettingsInSections { get; set; }
#endif
        /// <summary>disable editing of individual settings by specifying a comma-delimited list like &quot;samples_save,samples_format&quot;. The list of setting names can be found in the config.json file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FreezeSpecificSettings { get; set; }
#nullable restore
#else
        public string FreezeSpecificSettings { get; set; }
#endif
        /// <summary>GFPGAN directory</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GfpganDir { get; set; }
#nullable restore
#else
        public string GfpganDir { get; set; }
#endif
        /// <summary>GFPGAN model file name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GfpganModel { get; set; }
#nullable restore
#else
        public string GfpganModel { get; set; }
#endif
        /// <summary>Path to directory with GFPGAN model file(s).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GfpganModelsPath { get; set; }
#nullable restore
#else
        public string GfpganModelsPath { get; set; }
#endif
        /// <summary>The gpu_device_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GpuDeviceId { get; set; }
#nullable restore
#else
        public string GpuDeviceId { get; set; }
#endif
        /// <summary>add path to gradio&apos;s allowed_paths, make it possible to serve files from it</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? GradioAllowedPath { get; set; }
#nullable restore
#else
        public UntypedNode GradioAllowedPath { get; set; }
#endif
        /// <summary>set gradio authentication like &quot;username:password&quot;; or comma-delimit multiple like &quot;u1:p1,u2:p2,u3:p3&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GradioAuth { get; set; }
#nullable restore
#else
        public string GradioAuth { get; set; }
#endif
        /// <summary>set gradio authentication file path ex. &quot;/path/to/auth/file&quot; same auth format as --gradio-auth</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GradioAuthPath { get; set; }
#nullable restore
#else
        public string GradioAuthPath { get; set; }
#endif
        /// <summary>launch gradio with --debug option</summary>
        public bool? GradioDebug { get; set; }
        /// <summary>hide directory configuration from webui</summary>
        public bool? HideUiDirConfig { get; set; }
        /// <summary>Copy database file to and from /tmp when transacting (workaround for filesystems sqlite does not support)</summary>
        public bool? ImageBrowserTmpDb { get; set; }
        /// <summary>launch gradio with 0.0.0.0 as server name, allowing to respond to network requests</summary>
        public bool? Listen { get; set; }
        /// <summary>localizations directory</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalizationsDir { get; set; }
#nullable restore
#else
        public string LocalizationsDir { get; set; }
#endif
        /// <summary>log level; one of: CRITICAL, ERROR, WARNING, INFO, DEBUG</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Loglevel { get; set; }
#nullable restore
#else
        public string Loglevel { get; set; }
#endif
        /// <summary>launch.py argument: print a detailed log of what&apos;s happening at startup</summary>
        public bool? LogStartup { get; set; }
        /// <summary>Path to directory with LoRA networks</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoraDir { get; set; }
#nullable restore
#else
        public string LoraDir { get; set; }
#endif
        /// <summary>base path for all models</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModelRef { get; set; }
#nullable restore
#else
        public string ModelRef { get; set; }
#endif
        /// <summary>ngrok authtoken, alternative to gradio --share</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ngrok { get; set; }
#nullable restore
#else
        public string Ngrok { get; set; }
#endif
        /// <summary>The options to pass to ngrok in JSON format, e.g.: &apos;{&quot;authtoken_from_env&quot;:true, &quot;basic_auth&quot;:&quot;user:password&quot;, &quot;oauth_provider&quot;:&quot;google&quot;, &quot;oauth_allow_emails&quot;:&quot;user@asdf.com&quot;}&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.Flags_ngrok_options? NgrokOptions { get; set; }
#nullable restore
#else
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.Flags_ngrok_options NgrokOptions { get; set; }
#endif
        /// <summary>don&apos;t download SD1.5 model even if no model is found in --ckpt-dir</summary>
        public bool? NoDownloadSdModel { get; set; }
        /// <summary>Disables gradio queue; causes the webpage to use http requests instead of websockets; was the default in earlier versions</summary>
        public bool? NoGradioQueue { get; set; }
        /// <summary>do not switch the model to 16-bit floats</summary>
        public bool? NoHalf { get; set; }
        /// <summary>disable sha256 hashing of checkpoints to help loading performance</summary>
        public bool? NoHashing { get; set; }
        /// <summary>use api=True to launch the API instead of the webui</summary>
        public bool? Nowebui { get; set; }
        /// <summary>install nightly onnxruntime-gpu with cu130 support</summary>
        public bool? OnnxruntimeGpu { get; set; }
        /// <summary>The persistent_patches property</summary>
        public bool? PersistentPatches { get; set; }
        /// <summary>The pin_shared_memory property</summary>
        public bool? PinSharedMemory { get; set; }
        /// <summary>launch gradio with given server port, you need root/admin rights for ports &lt; 1024, defaults to 7860 if available</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Port { get; set; }
#nullable restore
#else
        public string Port { get; set; }
#endif
        /// <summary>The pytorch_deterministic property</summary>
        public bool? PytorchDeterministic { get; set; }
        /// <summary>launch.py argument: install the appropriate version of torch even if you have some version already installed</summary>
        public bool? ReinstallTorch { get; set; }
        /// <summary>launch.py argument: install the appropriate version of xformers even if you have some version already installed</summary>
        public bool? ReinstallXformers { get; set; }
        /// <summary>install sageattention</summary>
        public bool? Sage { get; set; }
        /// <summary>The sage2_function property</summary>
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.SageAttentionFuncs? Sage2Function { get; set; }
        /// <summary>The sage_accum_dtype property</summary>
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_pv_accum_dtype? SageAccumDtype { get; set; }
        /// <summary>The sage_quant_gran property</summary>
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_qk_quant_gran? SageQuantGran { get; set; }
        /// <summary>The sage_quantization_backend property</summary>
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_quantization_backend? SageQuantizationBackend { get; set; }
        /// <summary>Sets hostname of server</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerName { get; set; }
#nullable restore
#else
        public string ServerName { get; set; }
#endif
        /// <summary>use share=True for gradio and make the UI accessible through their site</summary>
        public bool? Share { get; set; }
        /// <summary>launch.py argument: skip installation of packages</summary>
        public bool? SkipInstall { get; set; }
        /// <summary>launch.py argument: skip all environment preparation</summary>
        public bool? SkipPrepareEnvironment { get; set; }
        /// <summary>launch.py argument: do not check python version</summary>
        public bool? SkipPythonVersionCheck { get; set; }
        /// <summary>launch.py argument: do not check if CUDA is able to work properly</summary>
        public bool? SkipTorchCudaTest { get; set; }
        /// <summary>Do not check versions of torch and xformers</summary>
        public bool? SkipVersionCheck { get; set; }
        /// <summary>path or wildcard path of styles files, allow multiple entries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? StylesFile { get; set; }
#nullable restore
#else
        public UntypedNode StylesFile { get; set; }
#endif
        /// <summary>customize the subpath for gradio, use with reverse proxy</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subpath { get; set; }
#nullable restore
#else
        public string Subpath { get; set; }
#endif
        /// <summary>launches the UI with light or dark theme</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Theme { get; set; }
#nullable restore
#else
        public string Theme { get; set; }
#endif
        /// <summary>set timeout_keep_alive for uvicorn</summary>
        public int? TimeoutKeepAlive { get; set; }
        /// <summary>Partially enables TLS, requires --tls-keyfile to fully function</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TlsCertfile { get; set; }
#nullable restore
#else
        public string TlsCertfile { get; set; }
#endif
        /// <summary>Partially enables TLS, requires --tls-certfile to fully function</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TlsKeyfile { get; set; }
#nullable restore
#else
        public string TlsKeyfile { get; set; }
#endif
        /// <summary>filename to use for ui configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UiConfigFile { get; set; }
#nullable restore
#else
        public string UiConfigFile { get; set; }
#endif
        /// <summary>Don&apos;t load model to quickly launch UI</summary>
        public bool? UiDebugMode { get; set; }
        /// <summary>filename to use for ui settings</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UiSettingsFile { get; set; }
#nullable restore
#else
        public string UiSettingsFile { get; set; }
#endif
        /// <summary>The unet_in_bf16 property</summary>
        public bool? UnetInBf16 { get; set; }
        /// <summary>The unet_in_fp16 property</summary>
        public bool? UnetInFp16 { get; set; }
        /// <summary>The unet_in_fp8_e4m3fn property</summary>
        public bool? UnetInFp8E4m3fn { get; set; }
        /// <summary>The unet_in_fp8_e5m2 property</summary>
        public bool? UnetInFp8E5m2 { get; set; }
        /// <summary>launch.py argument: download updates for all extensions when starting the program</summary>
        public bool? UpdateAllExtensions { get; set; }
        /// <summary>use CPU as torch device for specified modules</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? UseCpu { get; set; }
#nullable restore
#else
        public UntypedNode UseCpu { get; set; }
#endif
        /// <summary>use Intel XPU as torch device</summary>
        public bool? UseIpex { get; set; }
        /// <summary>use textbox for seeds in UI (no up/down, but possible to input long seeds)</summary>
        public bool? UseTextboxSeed { get; set; }
        /// <summary>Use the uv package manager</summary>
        public bool? Uv { get; set; }
        /// <summary>Use the uv package manager with symlink</summary>
        public bool? UvSymlink { get; set; }
        /// <summary>Path to directory with VAE files</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VaeDir { get; set; }
#nullable restore
#else
        public string VaeDir { get; set; }
#endif
        /// <summary>The vae_in_bf16 property</summary>
        public bool? VaeInBf16 { get; set; }
        /// <summary>The vae_in_cpu property</summary>
        public bool? VaeInCpu { get; set; }
        /// <summary>The vae_in_fp16 property</summary>
        public bool? VaeInFp16 { get; set; }
        /// <summary>The vae_in_fp32 property</summary>
        public bool? VaeInFp32 { get; set; }
        /// <summary>Checkpoint to use as VAE; setting this argument disables all settings related to VAE</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VaePath { get; set; }
#nullable restore
#else
        public string VaePath { get; set; }
#endif
        /// <summary>install xformers for cross attention</summary>
        public bool? Xformers { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Models.Flags"/> and sets the default values.
        /// </summary>
        public Flags()
        {
            AdditionalData = new Dictionary<string, object>();
            Ckpt = @"D:\StableDiffusion\sd-webui-forge-classic\model.ckpt";
            CodeformerModelsPath = @"D:\StableDiffusion\sd-webui-forge-classic\models\Codeformer";
            Config = @"D:\StableDiffusion\sd-webui-forge-classic\configs\v1-inference.yaml";
            ControlnetLoglevel = "INFO";
            DataDir = @"D:\StableDiffusion\sd-webui-forge-classic";
            EmbeddingsDir = @"D:\StableDiffusion\sd-webui-forge-classic\models\embeddings";
            EsrganModelsPath = @"D:\StableDiffusion\sd-webui-forge-classic\models\ESRGAN";
            GfpganDir = "./GFPGAN";
            GfpganModelsPath = @"D:\StableDiffusion\sd-webui-forge-classic\models\GFPGAN";
            LocalizationsDir = @"D:\StableDiffusion\sd-webui-forge-classic\localizations";
            LoraDir = @"D:\StableDiffusion\sd-webui-forge-classic\models\Lora";
            Sage2Function = global::MobileDiffusion.Clients.SdForgeNeo.Models.SageAttentionFuncs.Auto;
            SageAccumDtype = global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_pv_accum_dtype.Fp32;
            SageQuantGran = global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_qk_quant_gran.Per_thread;
            SageQuantizationBackend = global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_quantization_backend.Triton;
            UiConfigFile = @"D:\StableDiffusion\sd-webui-forge-classic\ui-config.json";
            UiSettingsFile = @"D:\StableDiffusion\sd-webui-forge-classic\config.json";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Models.Flags"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MobileDiffusion.Clients.SdForgeNeo.Models.Flags CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MobileDiffusion.Clients.SdForgeNeo.Models.Flags();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "administrator", n => { Administrator = n.GetBoolValue(); } },
                { "adv_samplers", n => { AdvSamplers = n.GetBoolValue(); } },
                { "adv_xyz", n => { AdvXyz = n.GetBoolValue(); } },
                { "all_in_fp16", n => { AllInFp16 = n.GetBoolValue(); } },
                { "all_in_fp32", n => { AllInFp32 = n.GetBoolValue(); } },
                { "always_cpu", n => { AlwaysCpu = n.GetBoolValue(); } },
                { "always_gpu", n => { AlwaysGpu = n.GetBoolValue(); } },
                { "always_high_vram", n => { AlwaysHighVram = n.GetBoolValue(); } },
                { "always_low_vram", n => { AlwaysLowVram = n.GetBoolValue(); } },
                { "always_no_vram", n => { AlwaysNoVram = n.GetBoolValue(); } },
                { "always_normal_vram", n => { AlwaysNormalVram = n.GetBoolValue(); } },
                { "always_offload_from_vram", n => { AlwaysOffloadFromVram = n.GetBoolValue(); } },
                { "api", n => { Api = n.GetBoolValue(); } },
                { "api_auth", n => { ApiAuth = n.GetStringValue(); } },
                { "api_log", n => { ApiLog = n.GetBoolValue(); } },
                { "api_server_stop", n => { ApiServerStop = n.GetBoolValue(); } },
                { "attention_pytorch", n => { AttentionPytorch = n.GetBoolValue(); } },
                { "autolaunch", n => { Autolaunch = n.GetBoolValue(); } },
                { "ckpt", n => { Ckpt = n.GetStringValue(); } },
                { "ckpt_dir", n => { CkptDir = n.GetStringValue(); } },
                { "clip_in_fp16", n => { ClipInFp16 = n.GetBoolValue(); } },
                { "clip_in_fp32", n => { ClipInFp32 = n.GetBoolValue(); } },
                { "clip_in_fp8_e4m3fn", n => { ClipInFp8E4m3fn = n.GetBoolValue(); } },
                { "clip_in_fp8_e5m2", n => { ClipInFp8E5m2 = n.GetBoolValue(); } },
                { "clip_in_gpu", n => { ClipInGpu = n.GetBoolValue(); } },
                { "codeformer_models_path", n => { CodeformerModelsPath = n.GetStringValue(); } },
                { "config", n => { Config = n.GetStringValue(); } },
                { "controlnet_dir", n => { ControlnetDir = n.GetStringValue(); } },
                { "controlnet_loglevel", n => { ControlnetLoglevel = n.GetStringValue(); } },
                { "controlnet_preprocessor_models_dir", n => { ControlnetPreprocessorModelsDir = n.GetStringValue(); } },
                { "cors_allow_origins", n => { CorsAllowOrigins = n.GetStringValue(); } },
                { "cors_allow_origins_regex", n => { CorsAllowOriginsRegex = n.GetStringValue(); } },
                { "cuda_malloc", n => { CudaMalloc = n.GetBoolValue(); } },
                { "cuda_stream", n => { CudaStream = n.GetBoolValue(); } },
                { "data_dir", n => { DataDir = n.GetStringValue(); } },
                { "device_id", n => { DeviceId = n.GetStringValue(); } },
                { "directml", n => { Directml = n.GetBoolValue(); } },
                { "disable_all_extensions", n => { DisableAllExtensions = n.GetBoolValue(); } },
                { "disable_attention_upcast", n => { DisableAttentionUpcast = n.GetBoolValue(); } },
                { "disable_console_progressbars", n => { DisableConsoleProgressbars = n.GetBoolValue(); } },
                { "disable_extra_extensions", n => { DisableExtraExtensions = n.GetBoolValue(); } },
                { "disable_flash", n => { DisableFlash = n.GetBoolValue(); } },
                { "disable_ipex_hijack", n => { DisableIpexHijack = n.GetBoolValue(); } },
                { "disable_nan_check", n => { DisableNanCheck = n.GetBoolValue(); } },
                { "disable_safe_unpickle", n => { DisableSafeUnpickle = n.GetBoolValue(); } },
                { "disable_sage", n => { DisableSage = n.GetBoolValue(); } },
                { "disable_tls_verify", n => { DisableTlsVerify = n.GetStringValue(); } },
                { "disable_xformers", n => { DisableXformers = n.GetBoolValue(); } },
                { "dump_sysinfo", n => { DumpSysinfo = n.GetBoolValue(); } },
                { "embeddings_dir", n => { EmbeddingsDir = n.GetStringValue(); } },
                { "enable_insecure_extension_access", n => { EnableInsecureExtensionAccess = n.GetBoolValue(); } },
                { "esrgan_models_path", n => { EsrganModelsPath = n.GetStringValue(); } },
                { "f", n => { F = n.GetBoolValue(); } },
                { "fast_fp16", n => { FastFp16 = n.GetBoolValue(); } },
                { "flash", n => { Flash = n.GetBoolValue(); } },
                { "forge_ref_a1111_home", n => { ForgeRefA1111Home = n.GetStringValue(); } },
                { "fps", n => { Fps = n.GetIntValue(); } },
                { "freeze_settings", n => { FreezeSettings = n.GetBoolValue(); } },
                { "freeze_settings_in_sections", n => { FreezeSettingsInSections = n.GetStringValue(); } },
                { "freeze_specific_settings", n => { FreezeSpecificSettings = n.GetStringValue(); } },
                { "gfpgan_dir", n => { GfpganDir = n.GetStringValue(); } },
                { "gfpgan_model", n => { GfpganModel = n.GetStringValue(); } },
                { "gfpgan_models_path", n => { GfpganModelsPath = n.GetStringValue(); } },
                { "gpu_device_id", n => { GpuDeviceId = n.GetStringValue(); } },
                { "gradio_allowed_path", n => { GradioAllowedPath = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "gradio_auth", n => { GradioAuth = n.GetStringValue(); } },
                { "gradio_auth_path", n => { GradioAuthPath = n.GetStringValue(); } },
                { "gradio_debug", n => { GradioDebug = n.GetBoolValue(); } },
                { "hide_ui_dir_config", n => { HideUiDirConfig = n.GetBoolValue(); } },
                { "image_browser_tmp_db", n => { ImageBrowserTmpDb = n.GetBoolValue(); } },
                { "listen", n => { Listen = n.GetBoolValue(); } },
                { "localizations_dir", n => { LocalizationsDir = n.GetStringValue(); } },
                { "log_startup", n => { LogStartup = n.GetBoolValue(); } },
                { "loglevel", n => { Loglevel = n.GetStringValue(); } },
                { "lora_dir", n => { LoraDir = n.GetStringValue(); } },
                { "model_ref", n => { ModelRef = n.GetStringValue(); } },
                { "ngrok", n => { Ngrok = n.GetStringValue(); } },
                { "ngrok_options", n => { NgrokOptions = n.GetObjectValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.Flags_ngrok_options>(global::MobileDiffusion.Clients.SdForgeNeo.Models.Flags_ngrok_options.CreateFromDiscriminatorValue); } },
                { "no_download_sd_model", n => { NoDownloadSdModel = n.GetBoolValue(); } },
                { "no_gradio_queue", n => { NoGradioQueue = n.GetBoolValue(); } },
                { "no_half", n => { NoHalf = n.GetBoolValue(); } },
                { "no_hashing", n => { NoHashing = n.GetBoolValue(); } },
                { "nowebui", n => { Nowebui = n.GetBoolValue(); } },
                { "onnxruntime_gpu", n => { OnnxruntimeGpu = n.GetBoolValue(); } },
                { "persistent_patches", n => { PersistentPatches = n.GetBoolValue(); } },
                { "pin_shared_memory", n => { PinSharedMemory = n.GetBoolValue(); } },
                { "port", n => { Port = n.GetStringValue(); } },
                { "pytorch_deterministic", n => { PytorchDeterministic = n.GetBoolValue(); } },
                { "reinstall_torch", n => { ReinstallTorch = n.GetBoolValue(); } },
                { "reinstall_xformers", n => { ReinstallXformers = n.GetBoolValue(); } },
                { "sage", n => { Sage = n.GetBoolValue(); } },
                { "sage2_function", n => { Sage2Function = n.GetEnumValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.SageAttentionFuncs>(); } },
                { "sage_accum_dtype", n => { SageAccumDtype = n.GetEnumValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_pv_accum_dtype>(); } },
                { "sage_quant_gran", n => { SageQuantGran = n.GetEnumValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_qk_quant_gran>(); } },
                { "sage_quantization_backend", n => { SageQuantizationBackend = n.GetEnumValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_quantization_backend>(); } },
                { "server_name", n => { ServerName = n.GetStringValue(); } },
                { "share", n => { Share = n.GetBoolValue(); } },
                { "skip_install", n => { SkipInstall = n.GetBoolValue(); } },
                { "skip_prepare_environment", n => { SkipPrepareEnvironment = n.GetBoolValue(); } },
                { "skip_python_version_check", n => { SkipPythonVersionCheck = n.GetBoolValue(); } },
                { "skip_torch_cuda_test", n => { SkipTorchCudaTest = n.GetBoolValue(); } },
                { "skip_version_check", n => { SkipVersionCheck = n.GetBoolValue(); } },
                { "styles_file", n => { StylesFile = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "subpath", n => { Subpath = n.GetStringValue(); } },
                { "theme", n => { Theme = n.GetStringValue(); } },
                { "timeout_keep_alive", n => { TimeoutKeepAlive = n.GetIntValue(); } },
                { "tls_certfile", n => { TlsCertfile = n.GetStringValue(); } },
                { "tls_keyfile", n => { TlsKeyfile = n.GetStringValue(); } },
                { "ui_config_file", n => { UiConfigFile = n.GetStringValue(); } },
                { "ui_debug_mode", n => { UiDebugMode = n.GetBoolValue(); } },
                { "ui_settings_file", n => { UiSettingsFile = n.GetStringValue(); } },
                { "unet_in_bf16", n => { UnetInBf16 = n.GetBoolValue(); } },
                { "unet_in_fp16", n => { UnetInFp16 = n.GetBoolValue(); } },
                { "unet_in_fp8_e4m3fn", n => { UnetInFp8E4m3fn = n.GetBoolValue(); } },
                { "unet_in_fp8_e5m2", n => { UnetInFp8E5m2 = n.GetBoolValue(); } },
                { "update_all_extensions", n => { UpdateAllExtensions = n.GetBoolValue(); } },
                { "use_cpu", n => { UseCpu = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "use_ipex", n => { UseIpex = n.GetBoolValue(); } },
                { "use_textbox_seed", n => { UseTextboxSeed = n.GetBoolValue(); } },
                { "uv", n => { Uv = n.GetBoolValue(); } },
                { "uv_symlink", n => { UvSymlink = n.GetBoolValue(); } },
                { "vae_dir", n => { VaeDir = n.GetStringValue(); } },
                { "vae_in_bf16", n => { VaeInBf16 = n.GetBoolValue(); } },
                { "vae_in_cpu", n => { VaeInCpu = n.GetBoolValue(); } },
                { "vae_in_fp16", n => { VaeInFp16 = n.GetBoolValue(); } },
                { "vae_in_fp32", n => { VaeInFp32 = n.GetBoolValue(); } },
                { "vae_path", n => { VaePath = n.GetStringValue(); } },
                { "xformers", n => { Xformers = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("administrator", Administrator);
            writer.WriteBoolValue("adv_samplers", AdvSamplers);
            writer.WriteBoolValue("adv_xyz", AdvXyz);
            writer.WriteBoolValue("all_in_fp16", AllInFp16);
            writer.WriteBoolValue("all_in_fp32", AllInFp32);
            writer.WriteBoolValue("always_cpu", AlwaysCpu);
            writer.WriteBoolValue("always_gpu", AlwaysGpu);
            writer.WriteBoolValue("always_high_vram", AlwaysHighVram);
            writer.WriteBoolValue("always_low_vram", AlwaysLowVram);
            writer.WriteBoolValue("always_normal_vram", AlwaysNormalVram);
            writer.WriteBoolValue("always_no_vram", AlwaysNoVram);
            writer.WriteBoolValue("always_offload_from_vram", AlwaysOffloadFromVram);
            writer.WriteBoolValue("api", Api);
            writer.WriteStringValue("api_auth", ApiAuth);
            writer.WriteBoolValue("api_log", ApiLog);
            writer.WriteBoolValue("api_server_stop", ApiServerStop);
            writer.WriteBoolValue("attention_pytorch", AttentionPytorch);
            writer.WriteBoolValue("autolaunch", Autolaunch);
            writer.WriteStringValue("ckpt", Ckpt);
            writer.WriteStringValue("ckpt_dir", CkptDir);
            writer.WriteBoolValue("clip_in_fp16", ClipInFp16);
            writer.WriteBoolValue("clip_in_fp32", ClipInFp32);
            writer.WriteBoolValue("clip_in_fp8_e4m3fn", ClipInFp8E4m3fn);
            writer.WriteBoolValue("clip_in_fp8_e5m2", ClipInFp8E5m2);
            writer.WriteBoolValue("clip_in_gpu", ClipInGpu);
            writer.WriteStringValue("codeformer_models_path", CodeformerModelsPath);
            writer.WriteStringValue("config", Config);
            writer.WriteStringValue("controlnet_dir", ControlnetDir);
            writer.WriteStringValue("controlnet_loglevel", ControlnetLoglevel);
            writer.WriteStringValue("controlnet_preprocessor_models_dir", ControlnetPreprocessorModelsDir);
            writer.WriteStringValue("cors_allow_origins", CorsAllowOrigins);
            writer.WriteStringValue("cors_allow_origins_regex", CorsAllowOriginsRegex);
            writer.WriteBoolValue("cuda_malloc", CudaMalloc);
            writer.WriteBoolValue("cuda_stream", CudaStream);
            writer.WriteStringValue("data_dir", DataDir);
            writer.WriteStringValue("device_id", DeviceId);
            writer.WriteBoolValue("directml", Directml);
            writer.WriteBoolValue("disable_all_extensions", DisableAllExtensions);
            writer.WriteBoolValue("disable_attention_upcast", DisableAttentionUpcast);
            writer.WriteBoolValue("disable_console_progressbars", DisableConsoleProgressbars);
            writer.WriteBoolValue("disable_extra_extensions", DisableExtraExtensions);
            writer.WriteBoolValue("disable_flash", DisableFlash);
            writer.WriteBoolValue("disable_ipex_hijack", DisableIpexHijack);
            writer.WriteBoolValue("disable_nan_check", DisableNanCheck);
            writer.WriteBoolValue("disable_safe_unpickle", DisableSafeUnpickle);
            writer.WriteBoolValue("disable_sage", DisableSage);
            writer.WriteStringValue("disable_tls_verify", DisableTlsVerify);
            writer.WriteBoolValue("disable_xformers", DisableXformers);
            writer.WriteBoolValue("dump_sysinfo", DumpSysinfo);
            writer.WriteStringValue("embeddings_dir", EmbeddingsDir);
            writer.WriteBoolValue("enable_insecure_extension_access", EnableInsecureExtensionAccess);
            writer.WriteStringValue("esrgan_models_path", EsrganModelsPath);
            writer.WriteBoolValue("f", F);
            writer.WriteBoolValue("fast_fp16", FastFp16);
            writer.WriteBoolValue("flash", Flash);
            writer.WriteStringValue("forge_ref_a1111_home", ForgeRefA1111Home);
            writer.WriteIntValue("fps", Fps);
            writer.WriteBoolValue("freeze_settings", FreezeSettings);
            writer.WriteStringValue("freeze_settings_in_sections", FreezeSettingsInSections);
            writer.WriteStringValue("freeze_specific_settings", FreezeSpecificSettings);
            writer.WriteStringValue("gfpgan_dir", GfpganDir);
            writer.WriteStringValue("gfpgan_model", GfpganModel);
            writer.WriteStringValue("gfpgan_models_path", GfpganModelsPath);
            writer.WriteStringValue("gpu_device_id", GpuDeviceId);
            writer.WriteObjectValue<UntypedNode>("gradio_allowed_path", GradioAllowedPath);
            writer.WriteStringValue("gradio_auth", GradioAuth);
            writer.WriteStringValue("gradio_auth_path", GradioAuthPath);
            writer.WriteBoolValue("gradio_debug", GradioDebug);
            writer.WriteBoolValue("hide_ui_dir_config", HideUiDirConfig);
            writer.WriteBoolValue("image_browser_tmp_db", ImageBrowserTmpDb);
            writer.WriteBoolValue("listen", Listen);
            writer.WriteStringValue("localizations_dir", LocalizationsDir);
            writer.WriteStringValue("loglevel", Loglevel);
            writer.WriteBoolValue("log_startup", LogStartup);
            writer.WriteStringValue("lora_dir", LoraDir);
            writer.WriteStringValue("model_ref", ModelRef);
            writer.WriteStringValue("ngrok", Ngrok);
            writer.WriteObjectValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.Flags_ngrok_options>("ngrok_options", NgrokOptions);
            writer.WriteBoolValue("no_download_sd_model", NoDownloadSdModel);
            writer.WriteBoolValue("no_gradio_queue", NoGradioQueue);
            writer.WriteBoolValue("no_half", NoHalf);
            writer.WriteBoolValue("no_hashing", NoHashing);
            writer.WriteBoolValue("nowebui", Nowebui);
            writer.WriteBoolValue("onnxruntime_gpu", OnnxruntimeGpu);
            writer.WriteBoolValue("persistent_patches", PersistentPatches);
            writer.WriteBoolValue("pin_shared_memory", PinSharedMemory);
            writer.WriteStringValue("port", Port);
            writer.WriteBoolValue("pytorch_deterministic", PytorchDeterministic);
            writer.WriteBoolValue("reinstall_torch", ReinstallTorch);
            writer.WriteBoolValue("reinstall_xformers", ReinstallXformers);
            writer.WriteBoolValue("sage", Sage);
            writer.WriteEnumValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.SageAttentionFuncs>("sage2_function", Sage2Function);
            writer.WriteEnumValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_pv_accum_dtype>("sage_accum_dtype", SageAccumDtype);
            writer.WriteEnumValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_qk_quant_gran>("sage_quant_gran", SageQuantGran);
            writer.WriteEnumValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.Sage_quantization_backend>("sage_quantization_backend", SageQuantizationBackend);
            writer.WriteStringValue("server_name", ServerName);
            writer.WriteBoolValue("share", Share);
            writer.WriteBoolValue("skip_install", SkipInstall);
            writer.WriteBoolValue("skip_prepare_environment", SkipPrepareEnvironment);
            writer.WriteBoolValue("skip_python_version_check", SkipPythonVersionCheck);
            writer.WriteBoolValue("skip_torch_cuda_test", SkipTorchCudaTest);
            writer.WriteBoolValue("skip_version_check", SkipVersionCheck);
            writer.WriteObjectValue<UntypedNode>("styles_file", StylesFile);
            writer.WriteStringValue("subpath", Subpath);
            writer.WriteStringValue("theme", Theme);
            writer.WriteIntValue("timeout_keep_alive", TimeoutKeepAlive);
            writer.WriteStringValue("tls_certfile", TlsCertfile);
            writer.WriteStringValue("tls_keyfile", TlsKeyfile);
            writer.WriteStringValue("ui_config_file", UiConfigFile);
            writer.WriteBoolValue("ui_debug_mode", UiDebugMode);
            writer.WriteStringValue("ui_settings_file", UiSettingsFile);
            writer.WriteBoolValue("unet_in_bf16", UnetInBf16);
            writer.WriteBoolValue("unet_in_fp16", UnetInFp16);
            writer.WriteBoolValue("unet_in_fp8_e4m3fn", UnetInFp8E4m3fn);
            writer.WriteBoolValue("unet_in_fp8_e5m2", UnetInFp8E5m2);
            writer.WriteBoolValue("update_all_extensions", UpdateAllExtensions);
            writer.WriteObjectValue<UntypedNode>("use_cpu", UseCpu);
            writer.WriteBoolValue("use_ipex", UseIpex);
            writer.WriteBoolValue("use_textbox_seed", UseTextboxSeed);
            writer.WriteBoolValue("uv", Uv);
            writer.WriteBoolValue("uv_symlink", UvSymlink);
            writer.WriteStringValue("vae_dir", VaeDir);
            writer.WriteBoolValue("vae_in_bf16", VaeInBf16);
            writer.WriteBoolValue("vae_in_cpu", VaeInCpu);
            writer.WriteBoolValue("vae_in_fp16", VaeInFp16);
            writer.WriteBoolValue("vae_in_fp32", VaeInFp32);
            writer.WriteStringValue("vae_path", VaePath);
            writer.WriteBoolValue("xformers", Xformers);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
