// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.Models
{
    /// <summary>An enumeration.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Sage_quantization_backend
    {
        [EnumMember(Value = "cuda")]
        #pragma warning disable CS1591
        Cuda,
        #pragma warning restore CS1591
        [EnumMember(Value = "triton")]
        #pragma warning disable CS1591
        Triton,
        #pragma warning restore CS1591
    }
}
