// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScriptInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of script&apos;s arguments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MobileDiffusion.Clients.SdForgeNeo.Models.ScriptArg>? Args { get; set; }
#nullable restore
#else
        public List<global::MobileDiffusion.Clients.SdForgeNeo.Models.ScriptArg> Args { get; set; }
#endif
        /// <summary>Flag specifying whether this script is an alwayson script</summary>
        public bool? IsAlwayson { get; set; }
        /// <summary>Flag specifying whether this script is an img2img script</summary>
        public bool? IsImg2img { get; set; }
        /// <summary>Script name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Models.ScriptInfo"/> and sets the default values.
        /// </summary>
        public ScriptInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Models.ScriptInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MobileDiffusion.Clients.SdForgeNeo.Models.ScriptInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MobileDiffusion.Clients.SdForgeNeo.Models.ScriptInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "args", n => { Args = n.GetCollectionOfObjectValues<global::MobileDiffusion.Clients.SdForgeNeo.Models.ScriptArg>(global::MobileDiffusion.Clients.SdForgeNeo.Models.ScriptArg.CreateFromDiscriminatorValue)?.AsList(); } },
                { "is_alwayson", n => { IsAlwayson = n.GetBoolValue(); } },
                { "is_img2img", n => { IsImg2img = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::MobileDiffusion.Clients.SdForgeNeo.Models.ScriptArg>("args", Args);
            writer.WriteBoolValue("is_alwayson", IsAlwayson);
            writer.WriteBoolValue("is_img2img", IsImg2img);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
