// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MobileDiffusion.Clients.SdForgeNeo.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StableDiffusionProcessingTxt2Img : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alwayson_scripts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_alwayson_scripts? AlwaysonScripts { get; set; }
#nullable restore
#else
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_alwayson_scripts AlwaysonScripts { get; set; }
#endif
        /// <summary>The batch_size property</summary>
        public int? BatchSize { get; set; }
        /// <summary>The cfg_scale property</summary>
        public double? CfgScale { get; set; }
        /// <summary>The comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_comments? Comments { get; set; }
#nullable restore
#else
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_comments Comments { get; set; }
#endif
        /// <summary>The denoising_strength property</summary>
        public double? DenoisingStrength { get; set; }
        /// <summary>The disable_extra_networks property</summary>
        public bool? DisableExtraNetworks { get; set; }
        /// <summary>The do_not_save_grid property</summary>
        public bool? DoNotSaveGrid { get; set; }
        /// <summary>The do_not_save_samples property</summary>
        public bool? DoNotSaveSamples { get; set; }
        /// <summary>The enable_hr property</summary>
        public bool? EnableHr { get; set; }
        /// <summary>The eta property</summary>
        public double? Eta { get; set; }
        /// <summary>The firstpass_image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstpassImage { get; set; }
#nullable restore
#else
        public string FirstpassImage { get; set; }
#endif
        /// <summary>The firstphase_height property</summary>
        public int? FirstphaseHeight { get; set; }
        /// <summary>The firstphase_width property</summary>
        public int? FirstphaseWidth { get; set; }
        /// <summary>The force_task_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForceTaskId { get; set; }
#nullable restore
#else
        public string ForceTaskId { get; set; }
#endif
        /// <summary>The height property</summary>
        public int? Height { get; set; }
        /// <summary>The hr_cfg_scale property</summary>
        public double? HrCfgScale { get; set; }
        /// <summary>The hr_checkpoint_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HrCheckpointName { get; set; }
#nullable restore
#else
        public string HrCheckpointName { get; set; }
#endif
        /// <summary>The hr_negative_prompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HrNegativePrompt { get; set; }
#nullable restore
#else
        public string HrNegativePrompt { get; set; }
#endif
        /// <summary>The hr_prompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HrPrompt { get; set; }
#nullable restore
#else
        public string HrPrompt { get; set; }
#endif
        /// <summary>The hr_rescale_cfg property</summary>
        public double? HrRescaleCfg { get; set; }
        /// <summary>The hr_resize_x property</summary>
        public int? HrResizeX { get; set; }
        /// <summary>The hr_resize_y property</summary>
        public int? HrResizeY { get; set; }
        /// <summary>The hr_sampler_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HrSamplerName { get; set; }
#nullable restore
#else
        public string HrSamplerName { get; set; }
#endif
        /// <summary>The hr_scale property</summary>
        public double? HrScale { get; set; }
        /// <summary>The hr_scheduler property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HrScheduler { get; set; }
#nullable restore
#else
        public string HrScheduler { get; set; }
#endif
        /// <summary>The hr_second_pass_steps property</summary>
        public int? HrSecondPassSteps { get; set; }
        /// <summary>The hr_upscaler property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HrUpscaler { get; set; }
#nullable restore
#else
        public string HrUpscaler { get; set; }
#endif
        /// <summary>The infotext property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Infotext { get; set; }
#nullable restore
#else
        public string Infotext { get; set; }
#endif
        /// <summary>The negative_prompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NegativePrompt { get; set; }
#nullable restore
#else
        public string NegativePrompt { get; set; }
#endif
        /// <summary>The n_iter property</summary>
        public int? NIter { get; set; }
        /// <summary>The override_settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_override_settings? OverrideSettings { get; set; }
#nullable restore
#else
        public global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_override_settings OverrideSettings { get; set; }
#endif
        /// <summary>The override_settings_restore_afterwards property</summary>
        public bool? OverrideSettingsRestoreAfterwards { get; set; }
        /// <summary>The prompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>The refiner_checkpoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefinerCheckpoint { get; set; }
#nullable restore
#else
        public string RefinerCheckpoint { get; set; }
#endif
        /// <summary>The refiner_switch_at property</summary>
        public double? RefinerSwitchAt { get; set; }
        /// <summary>The restore_faces property</summary>
        public bool? RestoreFaces { get; set; }
        /// <summary>The sampler_index property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SamplerIndex { get; set; }
#nullable restore
#else
        public string SamplerIndex { get; set; }
#endif
        /// <summary>The sampler_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SamplerName { get; set; }
#nullable restore
#else
        public string SamplerName { get; set; }
#endif
        /// <summary>The save_images property</summary>
        public bool? SaveImages { get; set; }
        /// <summary>The scheduler property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scheduler { get; set; }
#nullable restore
#else
        public string Scheduler { get; set; }
#endif
        /// <summary>The s_churn property</summary>
        public double? SChurn { get; set; }
        /// <summary>The script_args property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ScriptArgs { get; set; }
#nullable restore
#else
        public UntypedNode ScriptArgs { get; set; }
#endif
        /// <summary>The script_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScriptName { get; set; }
#nullable restore
#else
        public string ScriptName { get; set; }
#endif
        /// <summary>The seed property</summary>
        public long? Seed { get; set; }
        /// <summary>The seed_resize_from_h property</summary>
        public int? SeedResizeFromH { get; set; }
        /// <summary>The seed_resize_from_w property</summary>
        public int? SeedResizeFromW { get; set; }
        /// <summary>The send_images property</summary>
        public bool? SendImages { get; set; }
        /// <summary>The skip_early_cond property</summary>
        public double? SkipEarlyCond { get; set; }
        /// <summary>The s_min_uncond property</summary>
        public double? SMinUncond { get; set; }
        /// <summary>The s_noise property</summary>
        public double? SNoise { get; set; }
        /// <summary>The steps property</summary>
        public int? Steps { get; set; }
        /// <summary>The s_tmax property</summary>
        public double? STmax { get; set; }
        /// <summary>The s_tmin property</summary>
        public double? STmin { get; set; }
        /// <summary>The styles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Styles { get; set; }
#nullable restore
#else
        public List<string> Styles { get; set; }
#endif
        /// <summary>The subseed property</summary>
        public int? Subseed { get; set; }
        /// <summary>The subseed_strength property</summary>
        public double? SubseedStrength { get; set; }
        /// <summary>The tiling property</summary>
        public bool? Tiling { get; set; }
        /// <summary>The token_merging_ratio property</summary>
        public double? TokenMergingRatio { get; set; }
        /// <summary>The token_merging_ratio_hr property</summary>
        public double? TokenMergingRatioHr { get; set; }
        /// <summary>The width property</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img"/> and sets the default values.
        /// </summary>
        public StableDiffusionProcessingTxt2Img()
        {
            AdditionalData = new Dictionary<string, object>();
            SamplerIndex = "Euler";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alwayson_scripts", n => { AlwaysonScripts = n.GetObjectValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_alwayson_scripts>(global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_alwayson_scripts.CreateFromDiscriminatorValue); } },
                { "batch_size", n => { BatchSize = n.GetIntValue(); } },
                { "cfg_scale", n => { CfgScale = n.GetDoubleValue(); } },
                { "comments", n => { Comments = n.GetObjectValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_comments>(global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_comments.CreateFromDiscriminatorValue); } },
                { "denoising_strength", n => { DenoisingStrength = n.GetDoubleValue(); } },
                { "disable_extra_networks", n => { DisableExtraNetworks = n.GetBoolValue(); } },
                { "do_not_save_grid", n => { DoNotSaveGrid = n.GetBoolValue(); } },
                { "do_not_save_samples", n => { DoNotSaveSamples = n.GetBoolValue(); } },
                { "enable_hr", n => { EnableHr = n.GetBoolValue(); } },
                { "eta", n => { Eta = n.GetDoubleValue(); } },
                { "firstpass_image", n => { FirstpassImage = n.GetStringValue(); } },
                { "firstphase_height", n => { FirstphaseHeight = n.GetIntValue(); } },
                { "firstphase_width", n => { FirstphaseWidth = n.GetIntValue(); } },
                { "force_task_id", n => { ForceTaskId = n.GetStringValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "hr_cfg_scale", n => { HrCfgScale = n.GetDoubleValue(); } },
                { "hr_checkpoint_name", n => { HrCheckpointName = n.GetStringValue(); } },
                { "hr_negative_prompt", n => { HrNegativePrompt = n.GetStringValue(); } },
                { "hr_prompt", n => { HrPrompt = n.GetStringValue(); } },
                { "hr_rescale_cfg", n => { HrRescaleCfg = n.GetDoubleValue(); } },
                { "hr_resize_x", n => { HrResizeX = n.GetIntValue(); } },
                { "hr_resize_y", n => { HrResizeY = n.GetIntValue(); } },
                { "hr_sampler_name", n => { HrSamplerName = n.GetStringValue(); } },
                { "hr_scale", n => { HrScale = n.GetDoubleValue(); } },
                { "hr_scheduler", n => { HrScheduler = n.GetStringValue(); } },
                { "hr_second_pass_steps", n => { HrSecondPassSteps = n.GetIntValue(); } },
                { "hr_upscaler", n => { HrUpscaler = n.GetStringValue(); } },
                { "infotext", n => { Infotext = n.GetStringValue(); } },
                { "n_iter", n => { NIter = n.GetIntValue(); } },
                { "negative_prompt", n => { NegativePrompt = n.GetStringValue(); } },
                { "override_settings", n => { OverrideSettings = n.GetObjectValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_override_settings>(global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_override_settings.CreateFromDiscriminatorValue); } },
                { "override_settings_restore_afterwards", n => { OverrideSettingsRestoreAfterwards = n.GetBoolValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "refiner_checkpoint", n => { RefinerCheckpoint = n.GetStringValue(); } },
                { "refiner_switch_at", n => { RefinerSwitchAt = n.GetDoubleValue(); } },
                { "restore_faces", n => { RestoreFaces = n.GetBoolValue(); } },
                { "s_churn", n => { SChurn = n.GetDoubleValue(); } },
                { "s_min_uncond", n => { SMinUncond = n.GetDoubleValue(); } },
                { "s_noise", n => { SNoise = n.GetDoubleValue(); } },
                { "s_tmax", n => { STmax = n.GetDoubleValue(); } },
                { "s_tmin", n => { STmin = n.GetDoubleValue(); } },
                { "sampler_index", n => { SamplerIndex = n.GetStringValue(); } },
                { "sampler_name", n => { SamplerName = n.GetStringValue(); } },
                { "save_images", n => { SaveImages = n.GetBoolValue(); } },
                { "scheduler", n => { Scheduler = n.GetStringValue(); } },
                { "script_args", n => { ScriptArgs = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "script_name", n => { ScriptName = n.GetStringValue(); } },
                { "seed", n => { Seed = n.GetLongValue(); } },
                { "seed_resize_from_h", n => { SeedResizeFromH = n.GetIntValue(); } },
                { "seed_resize_from_w", n => { SeedResizeFromW = n.GetIntValue(); } },
                { "send_images", n => { SendImages = n.GetBoolValue(); } },
                { "skip_early_cond", n => { SkipEarlyCond = n.GetDoubleValue(); } },
                { "steps", n => { Steps = n.GetIntValue(); } },
                { "styles", n => { Styles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "subseed", n => { Subseed = n.GetIntValue(); } },
                { "subseed_strength", n => { SubseedStrength = n.GetDoubleValue(); } },
                { "tiling", n => { Tiling = n.GetBoolValue(); } },
                { "token_merging_ratio", n => { TokenMergingRatio = n.GetDoubleValue(); } },
                { "token_merging_ratio_hr", n => { TokenMergingRatioHr = n.GetDoubleValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_alwayson_scripts>("alwayson_scripts", AlwaysonScripts);
            writer.WriteIntValue("batch_size", BatchSize);
            writer.WriteDoubleValue("cfg_scale", CfgScale);
            writer.WriteObjectValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_comments>("comments", Comments);
            writer.WriteDoubleValue("denoising_strength", DenoisingStrength);
            writer.WriteBoolValue("disable_extra_networks", DisableExtraNetworks);
            writer.WriteBoolValue("do_not_save_grid", DoNotSaveGrid);
            writer.WriteBoolValue("do_not_save_samples", DoNotSaveSamples);
            writer.WriteBoolValue("enable_hr", EnableHr);
            writer.WriteDoubleValue("eta", Eta);
            writer.WriteStringValue("firstpass_image", FirstpassImage);
            writer.WriteIntValue("firstphase_height", FirstphaseHeight);
            writer.WriteIntValue("firstphase_width", FirstphaseWidth);
            writer.WriteStringValue("force_task_id", ForceTaskId);
            writer.WriteIntValue("height", Height);
            writer.WriteDoubleValue("hr_cfg_scale", HrCfgScale);
            writer.WriteStringValue("hr_checkpoint_name", HrCheckpointName);
            writer.WriteStringValue("hr_negative_prompt", HrNegativePrompt);
            writer.WriteStringValue("hr_prompt", HrPrompt);
            writer.WriteDoubleValue("hr_rescale_cfg", HrRescaleCfg);
            writer.WriteIntValue("hr_resize_x", HrResizeX);
            writer.WriteIntValue("hr_resize_y", HrResizeY);
            writer.WriteStringValue("hr_sampler_name", HrSamplerName);
            writer.WriteDoubleValue("hr_scale", HrScale);
            writer.WriteStringValue("hr_scheduler", HrScheduler);
            writer.WriteIntValue("hr_second_pass_steps", HrSecondPassSteps);
            writer.WriteStringValue("hr_upscaler", HrUpscaler);
            writer.WriteStringValue("infotext", Infotext);
            writer.WriteStringValue("negative_prompt", NegativePrompt);
            writer.WriteIntValue("n_iter", NIter);
            writer.WriteObjectValue<global::MobileDiffusion.Clients.SdForgeNeo.Models.StableDiffusionProcessingTxt2Img_override_settings>("override_settings", OverrideSettings);
            writer.WriteBoolValue("override_settings_restore_afterwards", OverrideSettingsRestoreAfterwards);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteStringValue("refiner_checkpoint", RefinerCheckpoint);
            writer.WriteDoubleValue("refiner_switch_at", RefinerSwitchAt);
            writer.WriteBoolValue("restore_faces", RestoreFaces);
            writer.WriteStringValue("sampler_index", SamplerIndex);
            writer.WriteStringValue("sampler_name", SamplerName);
            writer.WriteBoolValue("save_images", SaveImages);
            writer.WriteStringValue("scheduler", Scheduler);
            writer.WriteDoubleValue("s_churn", SChurn);
            writer.WriteObjectValue<UntypedNode>("script_args", ScriptArgs);
            writer.WriteStringValue("script_name", ScriptName);
            writer.WriteLongValue("seed", Seed);
            writer.WriteIntValue("seed_resize_from_h", SeedResizeFromH);
            writer.WriteIntValue("seed_resize_from_w", SeedResizeFromW);
            writer.WriteBoolValue("send_images", SendImages);
            writer.WriteDoubleValue("skip_early_cond", SkipEarlyCond);
            writer.WriteDoubleValue("s_min_uncond", SMinUncond);
            writer.WriteDoubleValue("s_noise", SNoise);
            writer.WriteIntValue("steps", Steps);
            writer.WriteDoubleValue("s_tmax", STmax);
            writer.WriteDoubleValue("s_tmin", STmin);
            writer.WriteCollectionOfPrimitiveValues<string>("styles", Styles);
            writer.WriteIntValue("subseed", Subseed);
            writer.WriteDoubleValue("subseed_strength", SubseedStrength);
            writer.WriteBoolValue("tiling", Tiling);
            writer.WriteDoubleValue("token_merging_ratio", TokenMergingRatio);
            writer.WriteDoubleValue("token_merging_ratio_hr", TokenMergingRatioHr);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
